In [1]:
import csv
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', 1130)
pd.set_option('display.max_columns', 550)
pd.set_option('display.width', 1000)

NYPD Complaint Data Historic" dataset downloaded from https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i , and loaded into nyc_crime DataFrame below.

In [3]:
#NYC Crime Data downloaded from https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i
nyc_data_path = open('/Users/DanLoew/Documents/Academia/Springboard/NYPD_Complaint_Data_Historic.csv', 'r')
nyc_crime = pd.read_csv(nyc_data_path)

/Users/DanLoew/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
#inspect what column 18 is as it was warned above as having mixed data types
nyc_crime.columns[18]

'PARKS_NM'

In [5]:
#inspect what column 20 is as it was warned above as having mixed data types
nyc_crime.columns[20]

'HOUSING_PSA'

There are too many different data values for the 'PARKS_NM' and 'HOUSING _PSA' variables to be split into binary machine variable labels (e.g., with get_dummies()), they aren't well labeled, and its not at all
clear what 'HOUSING_PSA' is describing from the data dictionary. So these two variables are dropped from the DataFrame.

In [6]:
nyc_crime = nyc_crime.drop(columns=['PARKS_NM', 'HOUSING_PSA'])

This data cleaning run is to create a cleaned DataFrame of the entire set, and then take samples for the inferential statistics and hypothesis testing portions of the capstone project. 

A first look through the DataFrame using .head(), .tail(), .shape, .info(), .describe(), and .columns.

In [7]:
nyc_crime.head()

CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  ADDR_PCT_CD      RPT_DT  KY_CD                      OFNS_DESC  PD_CD                                      PD_DESC CRM_ATPT_CPTD_CD   LAW_CAT_CD    BORO_NM LOC_OF_OCCUR_DESC               PREM_TYP_DESC           JURIS_DESC  JURISDICTION_CODE               HADEVELOPT  X_COORD_CD  Y_COORD_CD SUSP_AGE_GROUP       SUSP_RACE SUSP_SEX  TRANSIT_DISTRICT   Latitude  Longitude                        Lat_Lon              PATROL_BORO STATION_NAME VIC_AGE_GROUP        VIC_RACE VIC_SEX
0   577055921   12/31/2018     19:00:00   12/31/2018     19:35:00         75.0  12/31/2018    361  OFF. AGNST PUB ORD SENSBLTY &  639.0                      AGGRAVATED HARASSMENT 2        COMPLETED  MISDEMEANOR   BROOKLYN            INSIDE  RESIDENCE - PUBLIC HOUSING  N.Y. HOUSING POLICE                2.0  EAST NEW YORK CITY LINE   1019655.0    182468.0            <18           BLACK        F               NaN  40.667447 -73.872377  (40.667446665, -73.872377258)  PATROL BORO BKLYN NORTH          NaN         18-24           BLACK       M
1   311304275   12/31/2018     15:00:00   12/31/2018     16:00:00         41.0  12/31/2018    344   ASSAULT 3 & RELATED OFFENSES  101.0                                    ASSAULT 3        COMPLETED  MISDEMEANOR      BRONX            INSIDE                      STREET     N.Y. POLICE DEPT                0.0                      NaN   1015845.0    236500.0          25-44  WHITE HISPANIC        F               NaN  40.815765 -73.885857  (40.815765327, -73.885857339)        PATROL BORO BRONX          NaN         18-24  WHITE HISPANIC       F
2   427481098   12/31/2018     18:00:00   12/31/2018     18:30:00         14.0  12/31/2018    109                  GRAND LARCENY  410.0  LARCENY,GRAND FROM RETAIL STORE, UNATTENDED        COMPLETED       FELONY  MANHATTAN            INSIDE           CLOTHING/BOUTIQUE     N.Y. POLICE DEPT                0.0                      NaN    988318.0    212070.0            NaN             NaN      NaN               NaN  40.748767 -73.985320  (40.748767014, -73.985319659)    PATROL BORO MAN SOUTH          NaN         18-24         UNKNOWN       F
3   212387335   12/31/2018     16:50:00   12/31/2018     17:00:00         81.0  12/31/2018    106                 FELONY ASSAULT  109.0                     ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED       FELONY   BROOKLYN            INSIDE      RESIDENCE - APT. HOUSE     N.Y. POLICE DEPT                0.0                      NaN   1006734.0    188708.0          25-44           BLACK        M               NaN  40.684616 -73.918933  (40.684616294, -73.918932657)  PATROL BORO BKLYN NORTH          NaN         25-44           BLACK       M
4   629543587   12/31/2018     00:45:00   12/31/2018     01:00:00         26.0  12/31/2018    344   ASSAULT 3 & RELATED OFFENSES  101.0                                    ASSAULT 3        COMPLETED  MISDEMEANOR  MANHATTAN            INSIDE                       OTHER     N.Y. POLICE DEPT                0.0                      NaN    994261.0    232730.0          18-24           BLACK        F               NaN  40.805469 -73.963840  (40.805468548, -73.963840045)    PATROL BORO MAN NORTH          NaN         25-44  WHITE HISPANIC       M

In [8]:
nyc_crime.tail()

CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM  ADDR_PCT_CD      RPT_DT  KY_CD                       OFNS_DESC  PD_CD                           PD_DESC CRM_ATPT_CPTD_CD   LAW_CAT_CD    BORO_NM LOC_OF_OCCUR_DESC           PREM_TYP_DESC        JURIS_DESC  JURISDICTION_CODE HADEVELOPT  X_COORD_CD  Y_COORD_CD SUSP_AGE_GROUP                 SUSP_RACE SUSP_SEX  TRANSIT_DISTRICT   Latitude  Longitude                        Lat_Lon               PATROL_BORO STATION_NAME VIC_AGE_GROUP                  VIC_RACE VIC_SEX
6500865   608025222          NaN     18:00:00          NaN          NaN         23.0  06/06/2014    578                   HARRASSMENT 2  638.0             HARASSMENT,SUBD 3,4,5        COMPLETED    VIOLATION  MANHATTAN            INSIDE  RESIDENCE - APT. HOUSE  N.Y. POLICE DEPT                0.0        NaN   1001924.0    227875.0            NaN                     BLACK        F               NaN  40.792131 -73.936173  (40.792130892, -73.936172792)     PATROL BORO MAN NORTH          NaN         25-44                     BLACK       M
6500866   347331285          NaN     23:55:00   11/21/2014     00:05:00          7.0  11/21/2014    344    ASSAULT 3 & RELATED OFFENSES  101.0                         ASSAULT 3        COMPLETED  MISDEMEANOR  MANHATTAN          FRONT OF                  STREET  N.Y. POLICE DEPT                0.0        NaN    988082.0    200814.0            NaN                   UNKNOWN        M               NaN  40.717872 -73.986178  (40.717872161, -73.986177815)     PATROL BORO MAN SOUTH          NaN         25-44            WHITE HISPANIC       M
6500867   129237914          NaN     17:50:00          NaN          NaN         25.0  08/22/2015    341                   PETIT LARCENY  333.0    LARCENY,PETIT FROM STORE-SHOPL        COMPLETED  MISDEMEANOR  MANHATTAN            INSIDE     COMMERCIAL BUILDING  N.Y. POLICE DEPT                0.0        NaN   1001315.0    230818.0            NaN                     BLACK        M               NaN  40.800210 -73.938365  (40.800209825, -73.938364683)     PATROL BORO MAN NORTH          NaN           NaN                   UNKNOWN       D
6500868   230239029          NaN     09:25:00   02/20/2011     09:35:00        106.0  02/20/2011    351  CRIMINAL MISCHIEF & RELATED OF  259.0  CRIMINAL MISCHIEF,UNCLASSIFIED 4        COMPLETED  MISDEMEANOR     QUEENS            INSIDE         RESIDENCE-HOUSE  N.Y. POLICE DEPT                0.0        NaN   1037260.0    184030.0          18-24  ASIAN / PACIFIC ISLANDER        M               NaN  40.671646 -73.808905  (40.671646094, -73.808904508)  PATROL BORO QUEENS SOUTH          NaN         45-64  ASIAN / PACIFIC ISLANDER       F
6500869   215287089          NaN     01:00:00   03/06/2015     14:00:00         72.0  03/06/2015    351  CRIMINAL MISCHIEF & RELATED OF  254.0    MISCHIEF, CRIMINAL 4, OF MOTOR        COMPLETED  MISDEMEANOR   BROOKLYN          FRONT OF                  STREET  N.Y. POLICE DEPT                0.0        NaN    979853.0    171117.0            NaN                       NaN      NaN               NaN  40.636360 -74.015844  (40.636360331, -74.015843892)   PATROL BORO BKLYN SOUTH          NaN         45-64  ASIAN / PACIFIC ISLANDER       F

In [9]:
nyc_crime.shape

(6500870, 33)

In [10]:
nyc_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500870 entries, 0 to 6500869
Data columns (total 33 columns):
CMPLNT_NUM           int64
CMPLNT_FR_DT         object
CMPLNT_FR_TM         object
CMPLNT_TO_DT         object
CMPLNT_TO_TM         object
ADDR_PCT_CD          float64
RPT_DT               object
KY_CD                int64
OFNS_DESC            object
PD_CD                float64
PD_DESC              object
CRM_ATPT_CPTD_CD     object
LAW_CAT_CD           object
BORO_NM              object
LOC_OF_OCCUR_DESC    object
PREM_TYP_DESC        object
JURIS_DESC           object
JURISDICTION_CODE    float64
HADEVELOPT           object
X_COORD_CD           float64
Y_COORD_CD           float64
SUSP_AGE_GROUP       object
SUSP_RACE            object
SUSP_SEX             object
TRANSIT_DISTRICT     float64
Latitude             float64
Longitude            float64
Lat_Lon              object
PATROL_BORO          object
STATION_NAME         object
VIC_AGE_GROUP        object
VIC_RACE     

In [11]:
nyc_crime.describe(include='all')

CMPLNT_NUM CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM   ADDR_PCT_CD      RPT_DT         KY_CD      OFNS_DESC         PD_CD    PD_DESC CRM_ATPT_CPTD_CD   LAW_CAT_CD   BORO_NM LOC_OF_OCCUR_DESC PREM_TYP_DESC        JURIS_DESC  JURISDICTION_CODE   HADEVELOPT    X_COORD_CD    Y_COORD_CD SUSP_AGE_GROUP SUSP_RACE SUSP_SEX  TRANSIT_DISTRICT      Latitude     Longitude                        Lat_Lon        PATROL_BORO STATION_NAME VIC_AGE_GROUP VIC_RACE  VIC_SEX
count   6.500870e+06      6500215      6500822      4893769      4898069  6.498704e+06     6500870  6.500870e+06        6482065  6.495374e+06    6495374          6500863      6500870   6490352           5106061       6463167           6500870       6.495374e+06       323664  6.483531e+06  6.483531e+06        1909907   3278448  3145134     144110.000000  6.483531e+06  6.483531e+06                        6483531            6494917       144110       4862429  6500565  6500566
unique           NaN         7705         1441         6002         1441           NaN        4748           NaN             70           NaN        414                2            3         5                 5            72                25                NaN          279           NaN           NaN             95         8        3               NaN           NaN           NaN                         115631                  8          371           192        8        5
top              NaN   01/01/2010     12:00:00   10/17/2014     12:00:00           NaN  05/29/2007           NaN  PETIT LARCENY           NaN  ASSAULT 3        COMPLETED  MISDEMEANOR  BROOKLYN            INSIDE        STREET  N.Y. POLICE DEPT                NaN  CASTLE HILL           NaN           NaN          25-44     BLACK        M               NaN           NaN           NaN  (40.750430768, -73.989282176)  PATROL BORO BRONX   125 STREET         25-44  UNKNOWN        F
freq             NaN         2426       173998         1369        86413           NaN        1891           NaN        1072782           NaN     564308          6389307      3683269   1935028           3278342       2100852           5774513                NaN         7081           NaN           NaN         798541   1224987  1995894               NaN           NaN           NaN                          20668            1409156         7427       2110528  2186733  2539404
mean    5.500375e+08          NaN          NaN          NaN          NaN  6.334385e+01         NaN  2.951970e+02            NaN  4.158180e+02        NaN              NaN          NaN       NaN               NaN           NaN               NaN       7.149465e-01          NaN  1.004771e+06  2.069993e+05            NaN       NaN      NaN         13.634946  4.073480e+01 -7.392592e+01                            NaN                NaN          NaN           NaN      NaN      NaN
std     2.597725e+08          NaN          NaN          NaN          NaN  3.446073e+01         NaN  1.494116e+02            NaN  2.181813e+02        NaN              NaN          NaN       NaN               NaN           NaN               NaN       6.629446e+00          NaN  2.178907e+04  3.164418e+04            NaN       NaN      NaN         12.485026  8.675600e-02  7.857901e-02                            NaN                NaN          NaN           NaN      NaN      NaN
min     1.000001e+08          NaN          NaN          NaN          NaN  1.000000e+00         NaN  1.010000e+02            NaN  1.010000e+02        NaN              NaN          NaN       NaN               NaN           NaN               NaN       0.000000e+00          NaN  1.110000e+02  1.110000e+02            NaN       NaN      NaN          1.000000  4.011271e+01 -7.751921e+01                            NaN                NaN          NaN           NaN      NaN      NaN
25%     3.251865e+08          NaN          NaN          NaN          NaN  4.000000e+01         NaN  1.170000e+02            NaN  2.540000e+02        NaN              NaN          NaN    

The following section focuses on filling null values for those columns whose null values should not be dropped, and dropping null values for those columns whose null values do not need to be kept, in that order.

In [12]:
nyc_crime.isnull().sum()

CMPLNT_NUM                 0
CMPLNT_FR_DT             655
CMPLNT_FR_TM              48
CMPLNT_TO_DT         1607101
CMPLNT_TO_TM         1602801
ADDR_PCT_CD             2166
RPT_DT                     0
KY_CD                      0
OFNS_DESC              18805
PD_CD                   5496
PD_DESC                 5496
CRM_ATPT_CPTD_CD           7
LAW_CAT_CD                 0
BORO_NM                10518
LOC_OF_OCCUR_DESC    1394809
PREM_TYP_DESC          37703
JURIS_DESC                 0
JURISDICTION_CODE       5496
HADEVELOPT           6177206
X_COORD_CD             17339
Y_COORD_CD             17339
SUSP_AGE_GROUP       4590963
SUSP_RACE            3222422
SUSP_SEX             3355736
TRANSIT_DISTRICT     6356760
Latitude               17339
Longitude              17339
Lat_Lon                17339
PATROL_BORO             5953
STATION_NAME         6356760
VIC_AGE_GROUP        1638441
VIC_RACE                 305
VIC_SEX                  304
dtype: int64

In [13]:
nyc_crime.isna().sum()

CMPLNT_NUM                 0
CMPLNT_FR_DT             655
CMPLNT_FR_TM              48
CMPLNT_TO_DT         1607101
CMPLNT_TO_TM         1602801
ADDR_PCT_CD             2166
RPT_DT                     0
KY_CD                      0
OFNS_DESC              18805
PD_CD                   5496
PD_DESC                 5496
CRM_ATPT_CPTD_CD           7
LAW_CAT_CD                 0
BORO_NM                10518
LOC_OF_OCCUR_DESC    1394809
PREM_TYP_DESC          37703
JURIS_DESC                 0
JURISDICTION_CODE       5496
HADEVELOPT           6177206
X_COORD_CD             17339
Y_COORD_CD             17339
SUSP_AGE_GROUP       4590963
SUSP_RACE            3222422
SUSP_SEX             3355736
TRANSIT_DISTRICT     6356760
Latitude               17339
Longitude              17339
Lat_Lon                17339
PATROL_BORO             5953
STATION_NAME         6356760
VIC_AGE_GROUP        1638441
VIC_RACE                 305
VIC_SEX                  304
dtype: int64

The sum values match for both the .isnull().sum and .isna().sum() chained methods. Lists of floating data type columns that need to have their null values are identified below.

In [14]:
not_float_columns = [nyc_crime[c].dtype != float for c in nyc_crime.columns]

In [15]:
unknown_columns = list(nyc_crime.columns[(nyc_crime.isnull().sum()>0) & (not_float_columns)])
unknown_columns

['CMPLNT_FR_DT',
 'CMPLNT_FR_TM',
 'CMPLNT_TO_DT',
 'CMPLNT_TO_TM',
 'OFNS_DESC',
 'PD_DESC',
 'CRM_ATPT_CPTD_CD',
 'BORO_NM',
 'LOC_OF_OCCUR_DESC',
 'PREM_TYP_DESC',
 'HADEVELOPT',
 'SUSP_AGE_GROUP',
 'SUSP_RACE',
 'SUSP_SEX',
 'Lat_Lon',
 'PATROL_BORO',
 'STATION_NAME',
 'VIC_AGE_GROUP',
 'VIC_RACE',
 'VIC_SEX']

In [16]:
not_public_housing_related = ['HADEVELOPT']

In [17]:
complaint_from_date = ['CMPLNT_FR_DT']

In [18]:
complaint_from_time = ['CMPLNT_FR_TM']

In [19]:
complaint_to_date = ['CMPLNT_TO_DT']

In [20]:
complaint_to_time = ['CMPLNT_TO_TM']

In [21]:
fill_na_cols_not_transit_related = ['TRANSIT_DISTRICT', 'STATION_NAME']

In [22]:
fill_na_cols_unknown = ['ADDR_PCT_CD', 'OFNS_DESC', 'BORO_NM', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'SUSP_AGE_GROUP', 'SUSP_RACE', 
                       'SUSP_SEX', 'PATROL_BORO', 'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX', 'PD_CD', 'PD_DESC', 'JURISDICTION_CODE']

In [23]:
drop_na_cols = ['CRM_ATPT_CPTD_CD', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude', 'Lat_Lon']

In [24]:
nyc_crime[complaint_from_date] = nyc_crime[complaint_from_date].fillna(value='00/00/0000', axis=1)

In [25]:
nyc_crime[complaint_from_time] = nyc_crime[complaint_from_time].fillna(value='00:00:00', axis=1)

In [26]:
nyc_crime[complaint_to_date] = nyc_crime[complaint_to_date].fillna(value='00/00/0000', axis=1)

In [27]:
nyc_crime[complaint_to_time] = nyc_crime[complaint_to_time].fillna(value='00:00:00', axis=1)

In [28]:
nyc_crime[not_public_housing_related] = nyc_crime[not_public_housing_related].fillna(value='not_housing_devpt_crime', axis=1)

In [29]:
nyc_crime[fill_na_cols_not_transit_related] = nyc_crime[fill_na_cols_not_transit_related].fillna(value='not_transit_related', axis=1)

In [30]:
nyc_crime[fill_na_cols_unknown] = nyc_crime[fill_na_cols_unknown].fillna(value='unknown', axis=1)

In [31]:
nyc_crime = nyc_crime.dropna(axis=0)

In [32]:
nyc_crime.shape

(6483524, 33)

It can be seen below that there are no longer any missing values in the dataset.

In [33]:
nyc_crime.isna().sum()

CMPLNT_NUM           0
CMPLNT_FR_DT         0
CMPLNT_FR_TM         0
CMPLNT_TO_DT         0
CMPLNT_TO_TM         0
ADDR_PCT_CD          0
RPT_DT               0
KY_CD                0
OFNS_DESC            0
PD_CD                0
PD_DESC              0
CRM_ATPT_CPTD_CD     0
LAW_CAT_CD           0
BORO_NM              0
LOC_OF_OCCUR_DESC    0
PREM_TYP_DESC        0
JURIS_DESC           0
JURISDICTION_CODE    0
HADEVELOPT           0
X_COORD_CD           0
Y_COORD_CD           0
SUSP_AGE_GROUP       0
SUSP_RACE            0
SUSP_SEX             0
TRANSIT_DISTRICT     0
Latitude             0
Longitude            0
Lat_Lon              0
PATROL_BORO          0
STATION_NAME         0
VIC_AGE_GROUP        0
VIC_RACE             0
VIC_SEX              0
dtype: int64

A variable with missing data is spot-checked below.

In [34]:
nyc_crime['BORO_NM'].value_counts()

BROOKLYN         1929851
MANHATTAN        1554090
BRONX            1404794
QUEENS           1278577
STATEN ISLAND     306151
unknown            10061
Name: BORO_NM, dtype: int64

This section creates combined datetime variables, and duration variables, from the crime start date, crime start time, crime end date, and crime end time variables. First, the values of the respective component date and time variables are examined, and then combined into one variable of datetime format.

In [35]:
nyc_crime.CMPLNT_FR_DT.value_counts().head()

01/01/2010    2426
01/01/2008    2327
01/01/2011    2326
01/01/2014    2321
01/01/2016    2288
Name: CMPLNT_FR_DT, dtype: int64

In [36]:
nyc_crime.CMPLNT_FR_TM.value_counts().head()

12:00:00    173542
15:00:00    146287
18:00:00    140652
20:00:00    133364
17:00:00    130926
Name: CMPLNT_FR_TM, dtype: int64

In [37]:
nyc_crime['date_time_start'] = pd.to_datetime(nyc_crime['CMPLNT_FR_DT'] + ' ' + nyc_crime['CMPLNT_FR_TM'], errors='coerce')

In [38]:
#looking at the values, format and data type of this new variable
nyc_crime.date_time_start.head()

0   2018-12-31 19:00:00
1   2018-12-31 15:00:00
2   2018-12-31 18:00:00
3   2018-12-31 16:50:00
4   2018-12-31 00:45:00
Name: date_time_start, dtype: datetime64[ns]

In [39]:
nyc_crime.CMPLNT_TO_DT.value_counts().head()

00/00/0000    1600599
10/17/2014       1369
01/01/2014       1366
06/01/2016       1348
07/05/2018       1347
Name: CMPLNT_TO_DT, dtype: int64

In [40]:
nyc_crime.CMPLNT_TO_TM.value_counts().head()

00:00:00    1610146
12:00:00      86210
15:00:00      77782
08:00:00      75627
09:00:00      73304
Name: CMPLNT_TO_TM, dtype: int64

In [41]:
nyc_crime['date_time_end'] = pd.to_datetime(nyc_crime['CMPLNT_TO_DT'] + ' ' + nyc_crime['CMPLNT_TO_TM'], errors='coerce')

In [42]:
#looking at the values, format and data type of this new variable
nyc_crime.date_time_end.head()

0   2018-12-31 19:35:00
1   2018-12-31 16:00:00
2   2018-12-31 18:30:00
3   2018-12-31 17:00:00
4   2018-12-31 01:00:00
Name: date_time_end, dtype: datetime64[ns]

In the next section, the raw crime start time variables are used to create different time window variables that may be predictive of cannabis crimes. The start time variable 'CMPLNT_FR_TM' is used to define the time windows instead of the 'CMPLNT_TO_TM' variable, as all crimes have a start time in the data set but not necessarily an end time.

In [43]:
#to create a boolean mask for crimes that happen during the day
day_tw = (nyc_crime.CMPLNT_FR_TM >= '06:00:00') & (nyc_crime.CMPLNT_FR_TM <= '18:00:00') 

In [44]:
day_tw.value_counts()

True     3485125
False    2998399
Name: CMPLNT_FR_TM, dtype: int64

In [45]:
#to create a new binary column out of the daytime window, with values of '1' for daytime and '0' for nighttime.
nyc_crime['day_tw'] = day_tw.astype(int)

In [46]:
#to compare the values in the new column to the values in the boolean mask
nyc_crime.day_tw.value_counts()

1    3485125
0    2998399
Name: day_tw, dtype: int64

In [47]:
#for crimes done during the night
night_tw = (nyc_crime.CMPLNT_FR_TM < '06:00:00') | (nyc_crime.CMPLNT_FR_TM > '18:00:00')

In [48]:
#to create a new binary column out of the nighttime window, with values of '1' for nighttime and '0' for daytime.
nyc_crime['night_tw'] = night_tw.astype(int)

In [49]:
nyc_crime.night_tw.value_counts()

0    3485125
1    2998399
Name: night_tw, dtype: int64

In [50]:
#for crimes done during the early morning
early_morn = (nyc_crime.CMPLNT_FR_TM >= '06:00:00') & (nyc_crime.CMPLNT_FR_TM < '07:30:00')

In [51]:
#to create a new binary column out of the early morning window, with values of '1' for early morning and 
#'0' for not early morning.
nyc_crime['early_morn'] = early_morn.astype(int)

In [52]:
nyc_crime.early_morn.value_counts()

0    6314458
1     169066
Name: early_morn, dtype: int64

In [53]:
#for crimes done during the morning rush hour
morn_rush_hr = (nyc_crime.CMPLNT_FR_TM >= '07:30:00') & (nyc_crime.CMPLNT_FR_TM <= '09:00:00')

In [54]:
#to create a new binary column out of the morning rush hour window, with values of '1' for morning rush hour and 
#'0' for not morning rush hour.
nyc_crime['morn_rush_hr'] = morn_rush_hr.astype(int)

In [55]:
nyc_crime.morn_rush_hr.value_counts()

0    6089809
1     393715
Name: morn_rush_hr, dtype: int64

In [56]:
#for crimes done during the traditional workday
work_day = (nyc_crime.CMPLNT_FR_TM >= '09:00:00') & (nyc_crime.CMPLNT_FR_TM <= '18:00:00')

In [57]:
#to create a new binary column out of the work day window, with values of '1' for work day and 
#'0' for not work day.
nyc_crime['work_day'] = work_day.astype(int)

In [58]:
nyc_crime.work_day.value_counts()

0    3448436
1    3035088
Name: work_day, dtype: int64

In [59]:
#for crimes done during the lunch hour
lunch = (nyc_crime.CMPLNT_FR_TM >= '12:00:00') & (nyc_crime.CMPLNT_FR_TM <= '13:00:00')

In [60]:
#to create a new binary column out of the lunch hour window, with values of '1' for lunch hour and 
#'0' for not lunch hour.
nyc_crime['lunch_hr'] = lunch.astype(int)

In [61]:
nyc_crime.lunch_hr.value_counts()

0    6016472
1     467052
Name: lunch_hr, dtype: int64

In [62]:
#for crimes done during the evening rush hour; note the larger timespan is because this is NYC
eve_rush_hr = (nyc_crime.CMPLNT_FR_TM >= '16:30:00') & (nyc_crime.CMPLNT_FR_TM <= '19:00:00')

In [63]:
#to create a new binary column out of the evening rush hour window, with values of '1' for evening rush hour and 
#'0' for not evening rush hour.
nyc_crime['eve_rush_hr'] = eve_rush_hr.astype(int)

In [64]:
nyc_crime.eve_rush_hr.value_counts()

0    5447840
1    1035684
Name: eve_rush_hr, dtype: int64

In [65]:
#for crimes done during the dinner hour
dinner = (nyc_crime.CMPLNT_FR_TM >= '18:00:00') & (nyc_crime.CMPLNT_FR_TM <= '20:00:00')

In [66]:
#to create a new binary column out of the dinner hour window, with values of '1' for dinner hour and 
#'0' for not dinner hour.
nyc_crime['dinner'] = dinner.astype(int)

In [67]:
nyc_crime.dinner.value_counts()

0    5598765
1     884759
Name: dinner, dtype: int64

In [68]:
#for crimes done during the evening
evening = (nyc_crime.CMPLNT_FR_TM >= '20:00:00') & (nyc_crime.CMPLNT_FR_TM <= '22:00:00')

In [69]:
#to create a new binary column out of the evening window, with values of '1' for evening and 
#'0' for not evening.
nyc_crime['evening'] = evening.astype(int)

In [70]:
nyc_crime.evening.value_counts()

0    5674200
1     809324
Name: evening, dtype: int64

In [71]:
#for crimes done during the late night
late_night = (nyc_crime.CMPLNT_FR_TM > '22:00:00') | (nyc_crime.CMPLNT_FR_TM < '06:00:00')

In [72]:
#to create a new binary column out of the late night window, with values of '1' for late night and 
#'0' for not late night.
nyc_crime['late_night'] = late_night.astype(int)

In [73]:
nyc_crime.late_night.value_counts()

0    4905192
1    1578332
Name: late_night, dtype: int64

The following section encodes the distance of each cannabis crime from prominent NYC landmarks into continuous data variables. All latitudes and longitudes were found from Google searches. Both driving/walking/biking distances ("_taxi" variables) and shortest distances ("_crow" variables) are computed.

I plan on going back to create dictionary comprehensions using lists of values to code the distance from landmark data more efficiently and Pythonically.

In [74]:
#World Trade Center in downtown Manhattan
wtc_taxi = abs(nyc_crime.Latitude - 40.7127) + abs(nyc_crime.Longitude + 74.0134)#+ because the longitude is negative
wtc_crow = ((nyc_crime.Latitude - 40.7127)**2 + (nyc_crime.Longitude + 74.0134)**2)**0.5 #sqrt, pythagorean 
#New York Stock Exchange in downtown Manhattan
nyse_taxi = abs(nyc_crime.Latitude - 40.706877) + abs(nyc_crime.Longitude + 74.011265)
nyse_crow = ((nyc_crime.Latitude - 40.706877)**2 + (nyc_crime.Longitude + 74.011265)**2)**0.5
#Brooklyn Bridge
bk_bridge_taxi = abs(nyc_crime.Latitude - 40.7061) + abs(nyc_crime.Longitude + 73.9969)
bk_bridge_crow = ((nyc_crime.Latitude - 40.7061)**2 + (nyc_crime.Longitude + 73.9969)**2)**0.5
#New York City Hall in Manhattan
city_hall_taxi = abs(nyc_crime.Latitude - 40.7128) + abs(nyc_crime.Longitude + 74.0061)
city_hall_crow = ((nyc_crime.Latitude - 40.7128)**2 + (nyc_crime.Longitude + 74.0061)**2)**0.5
#Manhattan Bridge
manh_bridge_taxi = abs(nyc_crime.Latitude - 40.7075) + abs(nyc_crime.Longitude + 73.9908)
manh_bridge_crow = ((nyc_crime.Latitude - 40.7075)**2 + (nyc_crime.Longitude + 73.9908)**2)**0.5
#Williamsburg Bridge
will_bridge_taxi = abs(nyc_crime.Latitude - 40.7136) + abs(nyc_crime.Longitude + 73.9724)
will_bridge_crow = ((nyc_crime.Latitude - 40.7136)**2 + (nyc_crime.Longitude + 73.9724)**2)**0.5
#Washington Square Park in Manhattan
wash_sq_park_taxi = abs(nyc_crime.Latitude - 40.7308) + abs(nyc_crime.Longitude + 73.9973)
wash_sq_park_crow = ((nyc_crime.Latitude - 40.7308)**2 + (nyc_crime.Longitude + 73.9973)**2)**0.5
#Union Square in Manhattan
union_sq_taxi = abs(nyc_crime.Latitude - 40.7359) + abs(nyc_crime.Longitude + 73.9911)
union_sq_crow = ((nyc_crime.Latitude - 40.7359)**2 + (nyc_crime.Longitude + 73.9911)**2)**0.5
#Penn Station in Manhattan
penn_station_taxi = abs(nyc_crime.Latitude - 40.7506) + abs(nyc_crime.Longitude + 73.9935)
penn_station_crow = ((nyc_crime.Latitude - 40.7506)**2 + (nyc_crime.Longitude + 73.9935)**2)**0.5
#Times Square in Manhattan
times_sq_taxi = abs(nyc_crime.Latitude - 40.7590) + abs(nyc_crime.Longitude + 73.9845)
times_sq_crow = ((nyc_crime.Latitude - 40.7590)**2 + (nyc_crime.Longitude + 73.9845)**2)**0.5
#Rockefeller Center in Manhattan
rock_center_taxi = abs(nyc_crime.Latitude - 40.7587) + abs(nyc_crime.Longitude + 73.9787)
rock_center_crow = ((nyc_crime.Latitude - 40.7587)**2 + (nyc_crime.Longitude + 73.9787)**2)**0.5
#Empire State Building in Manhattan
empire_st_bldg_taxi = abs(nyc_crime.Latitude - 40.7484) + abs(nyc_crime.Longitude + 73.9857)
empire_st_bldg_crow = ((nyc_crime.Latitude - 40.7484)**2 + (nyc_crime.Longitude + 73.9857)**2)**0.5
#Lincoln Center in Manhattan
lincoln_ctr_taxi = abs(nyc_crime.Latitude - 40.7725) + abs(nyc_crime.Longitude + 73.9835)
lincoln_ctr_crow = ((nyc_crime.Latitude - 40.7725)**2 + (nyc_crime.Longitude + 73.9835)**2)**0.5
#Central Park, Manhattan
central_pk_taxi = abs(nyc_crime.Latitude - 40.7829) + abs(nyc_crime.Longitude + 73.9654)
central_pk_crow = ((nyc_crime.Latitude - 40.7829)**2 + (nyc_crime.Longitude + 73.9654)**2)**0.5
#Apollo Theatre, Harlem, Manhattan
apollo_th_taxi = abs(nyc_crime.Latitude - 40.8100) + abs(nyc_crime.Longitude + 73.9501)
apollo_th_crow = ((nyc_crime.Latitude - 40.8100)**2 + (nyc_crime.Longitude + 73.9501)**2)**0.5
#Yankee Stadium in the Bronx
yankee_stad_taxi = abs(nyc_crime.Latitude - 40.8296) + abs(nyc_crime.Longitude + 73.9262)
yankee_stad_crow = ((nyc_crime.Latitude - 40.8296)**2 + (nyc_crime.Longitude + 73.9262)**2)**0.5
#Mets Stadium in Queens
mets_stad_taxi = abs(nyc_crime.Latitude - 40.7547) + abs(nyc_crime.Longitude + 73.8457)
mets_stad_crow = ((nyc_crime.Latitude - 40.7547)**2 + (nyc_crime.Longitude + 73.8457)**2)**0.5
#Center of Queens borough
queens_taxi = abs(nyc_crime.Latitude - 40.7282) + abs(nyc_crime.Longitude + 73.7949)
queens_crow = ((nyc_crime.Latitude - 40.7282)**2 + (nyc_crime.Longitude + 73.7949)**2)**0.5
#Center of Prospect Park, Brooklyn
prospect_pk_taxi = abs(nyc_crime.Latitude - 40.6602) + abs(nyc_crime.Longitude + 73.9690)
prospect_pk_crow = ((nyc_crime.Latitude - 40.6602)**2 + (nyc_crime.Longitude + 73.9690)**2)**0.5
#Center of downtown Brooklyn
downtown_bk_taxi = abs(nyc_crime.Latitude - 40.6961) + abs(nyc_crime.Longitude + 73.9845)
downtown_bk_crow = ((nyc_crime.Latitude - 40.6961)**2 + (nyc_crime.Longitude + 73.9845)**2)**0.5
#Staten Island Ferry in Staten Island
si_ferry_taxi = abs(nyc_crime.Latitude - 40.579021) + abs(nyc_crime.Longitude + 74.151535)
si_ferry_crow = ((nyc_crime.Latitude - 40.579021)**2 + (nyc_crime.Longitude + 74.151535)**2)**0.5
#Port Authority Bus Terminal in Manhattan
port_authority_taxi = abs(nyc_crime.Latitude - 40.7572) + abs(nyc_crime.Longitude + 73.9908)
port_authority_crow = ((nyc_crime.Latitude - 40.7572)**2 + (nyc_crime.Longitude + 73.9908)**2)**0.5
#New York Police Department
nypd_hq_taxi = abs(nyc_crime.Latitude - 40.7120468) + abs(nyc_crime.Longitude + 74.0026395)
nypd_hq_crow = ((nyc_crime.Latitude - 40.7120468)**2 + (nyc_crime.Longitude + 74.0026395)**2)**0.5
#Manhattan Detention Center in downtown Manhattan
mdc_taxi = abs(nyc_crime.Latitude - 40.7170) + abs(nyc_crime.Longitude + 74.003)
mdc_crow = ((nyc_crime.Latitude - 40.7170)**2 + (nyc_crime.Longitude + 74.003)**2)**0.5
#Rikers Prison on Rikers Island
rikers_taxi = abs(nyc_crime.Latitude - 40.7931) + abs(nyc_crime.Longitude + 73.8860)
rikers_crow = ((nyc_crime.Latitude - 40.7931)**2 + (nyc_crime.Longitude + 73.8860)**2)**0.5
#New York Supreme Court
nysc_taxi = abs(nyc_crime.Latitude - 40.7144) + abs(nyc_crime.Longitude + 74.0020)
nysc_crow = ((nyc_crime.Latitude - 40.7144)**2 + (nyc_crime.Longitude + 74.0020)**2)**0.5
#think of prisons, homeless shelters, bail bonds offices, federal govt buildings, post offices

In [75]:
#creation of new column variables for the distance of each crime from all of these landmarks.
nyc_crime['wtc_taxi'] = wtc_taxi
nyc_crime['wtc_crow'] = wtc_crow
nyc_crime['nyse_taxi'] = nyse_taxi
nyc_crime['nyse_crow'] = nyse_crow
nyc_crime['bk_bridge_taxi'] = bk_bridge_taxi
nyc_crime['bk_bridge_crow'] = bk_bridge_crow
nyc_crime['city_hall_taxi'] = city_hall_taxi
nyc_crime['city_hall_crow'] = city_hall_crow
nyc_crime['manh_bridge_taxi'] = manh_bridge_taxi
nyc_crime['manh_bridge_crow'] = manh_bridge_crow
nyc_crime['will_bridge_taxi'] = will_bridge_taxi
nyc_crime['will_bridge_crow'] = will_bridge_crow
nyc_crime['wash_sq_park_taxi'] = wash_sq_park_taxi
nyc_crime['wash_sq_park_crow'] = wash_sq_park_crow
nyc_crime['union_sq_taxi'] = union_sq_taxi
nyc_crime['union_sq_crow'] = union_sq_crow
nyc_crime['penn_station_taxi'] = penn_station_taxi
nyc_crime['penn_station_crow'] = penn_station_crow
nyc_crime['times_sq_taxi'] = times_sq_taxi
nyc_crime['times_sq_crow'] = times_sq_crow
nyc_crime['rock_center_taxi'] = rock_center_taxi
nyc_crime['rock_center_crow'] = rock_center_crow
nyc_crime['empire_st_bldg_taxi'] = empire_st_bldg_taxi
nyc_crime['empire_st_bldg_crow'] = empire_st_bldg_crow
nyc_crime['lincoln_ctr_taxi'] = lincoln_ctr_taxi
nyc_crime['lincoln_ctr_crow'] = lincoln_ctr_crow
nyc_crime['central_pk_taxi'] = central_pk_taxi
nyc_crime['central_pk_crow'] = central_pk_crow
nyc_crime['apollo_th_taxi'] = apollo_th_taxi
nyc_crime['apollo_th_crow'] = apollo_th_crow
nyc_crime['yankee_stad_taxi'] = yankee_stad_taxi
nyc_crime['yankee_stad_crow'] = yankee_stad_crow
nyc_crime['mets_stad_taxi'] = mets_stad_taxi
nyc_crime['mets_stad_crow'] = mets_stad_crow
nyc_crime['queens_taxi'] = queens_taxi
nyc_crime['queens_crow'] = queens_crow
nyc_crime['prospect_pk_taxi'] = prospect_pk_taxi
nyc_crime['prospect_pk_crow'] = prospect_pk_crow
nyc_crime['downtown_bk_taxi'] = downtown_bk_taxi
nyc_crime['downtown_bk_crow'] = downtown_bk_crow
nyc_crime['si_ferry_taxi'] = si_ferry_taxi
nyc_crime['si_ferry_crow'] = si_ferry_crow
nyc_crime['port_authority_taxi'] = port_authority_taxi
nyc_crime['port_authority_crow'] = port_authority_crow
nyc_crime['nypd_hq_taxi'] = nypd_hq_taxi
nyc_crime['nypd_hq_crow'] = nypd_hq_crow
nyc_crime['mdc_taxi'] = mdc_taxi
nyc_crime['mdc_crow'] = mdc_crow
nyc_crime['rikers_taxi'] = rikers_taxi
nyc_crime['rikers_crow'] = rikers_crow
nyc_crime['nysc_taxi'] = nysc_taxi
nyc_crime['nysc_crow'] = nysc_crow

In [76]:
#created a duration variable for crimes that have separate start datetimes and end datetimes
nyc_crime['duration'] = nyc_crime.date_time_end - nyc_crime.date_time_start

In [77]:
duration_fill = ['duration']

In [78]:
nyc_crime[duration_fill] = nyc_crime[duration_fill].fillna('0 days 00:00:00', axis=1)

In [79]:
nyc_crime['duration'].value_counts()

0 days 00:00:00        1602547
0 days 00:05:00         661399
0 days 00:10:00         462280
0 days 00:15:00         288461
0 days 00:30:00         264974
0 days 00:00:00         256498
0 days 00:20:00         148771
0 days 01:00:00         134123
0 days 00:02:00         100016
0 days 00:01:00          84472
0 days 00:03:00          76714
0 days 00:04:00          62574
0 days 00:06:00          57338
0 days 00:07:00          55666
0 days 00:08:00          52269
0 days 02:00:00          50679
0 days 00:25:00          48776
0 days 00:09:00          40494
0 days 00:45:00          35003
0 days 01:30:00          33101
0 days 03:00:00          32420
0 days 00:11:00          29916
0 days 00:12:00          29658
0 days 00:40:00          29464
0 days 12:00:00          26693
0 days 00:13:00          26543
0 days 04:00:00          25072
0 days 00:14:00          24917
0 days 10:00:00          23178
0 days 08:00:00          23143
0 days 00:35:00          22824
0 days 11:00:00          22470
0 days 0

In [80]:
nyc_crime['duration'].isna().sum()

0

The next section extracts year, month, and date from the 'date_time_start' datetime variable into seperate column variables.

In [81]:
nyc_crime['start_year'] = nyc_crime.date_time_start.dt.year

The following command checks the year range in the data. Note that there are many cases that fall outside of the dataset's stated year range of 2006-2018. There are also obvious entry errors, so they will be coded to 'unknown' a little bit further down in the notebook.

In [82]:
nyc_crime.start_year.value_counts()

2007.0    535094
2008.0    528715
2006.0    512620
2009.0    511044
2010.0    510070
2012.0    504652
2011.0    498586
2013.0    495704
2014.0    491842
2015.0    478333
2016.0    477599
2017.0    466664
2018.0    452958
2005.0     10476
2004.0      2092
2003.0      1554
2002.0      1073
2001.0      1051
2000.0       911
1999.0       358
1998.0       241
1997.0       140
1996.0       132
1995.0        88
1994.0        77
1993.0        64
1992.0        49
1986.0        38
1990.0        37
1991.0        36
1989.0        32
1985.0        28
1966.0        26
1987.0        22
1988.0        20
1980.0        16
1979.0        16
1984.0        14
1968.0        14
1981.0        14
1977.0        14
1967.0        14
1975.0        13
1973.0        13
1914.0        11
1912.0        11
1971.0        11
1978.0        11
1983.0        11
1974.0        10
1982.0        10
1910.0         9
1913.0         9
1960.0         9
1915.0         9
1972.0         8
1969.0         7
1976.0         7
1911.0        

In [83]:
nyc_crime['start_month'] = nyc_crime.date_time_start.dt.month

In [84]:
#checking that every month of the calendar is represented.
nyc_crime.start_month.value_counts()

8.0     581561
7.0     581020
5.0     570201
10.0    567465
6.0     561203
9.0     557365
3.0     533059
1.0     529720
11.0    515708
4.0     513951
12.0    507464
2.0     464063
Name: start_month, dtype: int64

In [85]:
nyc_crime['start_day'] = nyc_crime.date_time_start.dt.day

In [86]:
#checking that every day of a month is represented.
nyc_crime.start_day.value_counts()

1.0     272396
15.0    221832
20.0    220120
10.0    217382
5.0     215105
12.0    213971
17.0    212920
2.0     211727
18.0    211644
14.0    211459
21.0    211420
13.0    211177
3.0     210944
11.0    210784
16.0    210733
9.0     210643
6.0     210476
7.0     210426
4.0     210323
8.0     210010
22.0    209930
23.0    209747
28.0    209108
19.0    207713
27.0    207154
24.0    206742
25.0    205817
26.0    204558
29.0    193034
30.0    192667
31.0    120818
Name: start_day, dtype: int64

In [87]:
nyc_crime['start_hour'] = nyc_crime.date_time_start.dt.hour

In [88]:
nyc_crime['start_hour'].value_counts()

15.0    389903
18.0    382541
17.0    373686
16.0    372208
19.0    368784
20.0    364958
12.0    359040
14.0    345344
21.0    331419
22.0    313615
0.0     311550
13.0    305541
23.0    289632
11.0    256442
10.0    250499
9.0     241392
1.0     222021
8.0     219398
2.0     179035
3.0     150528
7.0     135449
4.0     131854
6.0      95137
5.0      92804
Name: start_hour, dtype: int64

In [89]:
nyc_crime['start_minute'] = nyc_crime.date_time_start.dt.minute

In [90]:
nyc_crime['start_minute'].value_counts()

0.0     2308464
30.0    1103397
45.0     332567
15.0     330375
20.0     286944
50.0     281632
40.0     268848
10.0     227397
25.0     142180
5.0      130487
35.0     128143
55.0     126584
1.0       96618
18.0      20833
48.0      19732
8.0       19675
38.0      19371
58.0      19309
28.0      19033
12.0      17999
23.0      16606
43.0      16212
13.0      16124
22.0      15924
17.0      15886
14.0      15789
42.0      15723
24.0      15641
47.0      15541
7.0       15470
59.0      15454
2.0       15429
3.0       15389
27.0      15341
37.0      15165
9.0       15144
53.0      15030
19.0      14905
57.0      14902
44.0      14873
33.0      14771
52.0      14744
6.0       14519
32.0      14517
36.0      14470
39.0      14403
34.0      14245
26.0      14204
49.0      14203
4.0       14099
54.0      13960
16.0      13932
29.0      13924
11.0      13647
46.0      13422
56.0      13400
21.0      12457
41.0      11770
51.0      11474
31.0      10483
Name: start_minute, dtype: int64

The following section uses boolean masks and variable assignment to create new binary columns for major holidays that always fall on the same day of the year.

In [91]:
new_years_day = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 1)

In [92]:
nyc_crime['new_years_day'] = new_years_day.astype(int)
nyc_crime.new_years_day.value_counts()

0    6453141
1      30383
Name: new_years_day, dtype: int64

In [93]:
new_years_eve = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 31)

In [94]:
nyc_crime['new_years_eve'] = new_years_eve.astype(int)
nyc_crime.new_years_eve.value_counts()

0    6468721
1      14803
Name: new_years_eve, dtype: int64

In [95]:
christmas_eve = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 24)

In [96]:
nyc_crime['christmas_eve'] = christmas_eve.astype(int)
nyc_crime.christmas_eve.value_counts()

0    6469323
1      14201
Name: christmas_eve, dtype: int64

In [97]:
christmas = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 25)

In [98]:
nyc_crime['christmas'] = christmas.astype(int)

In [99]:
july_4th = (nyc_crime.start_month == 7) & (nyc_crime.start_day == 4)

In [100]:
nyc_crime['july_4th'] = july_4th.astype(int)

In [101]:
valentines = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 14)

In [102]:
nyc_crime['valentines'] = valentines.astype(int)

In [103]:
halloween = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 31)

In [104]:
nyc_crime['halloween'] = halloween.astype(int)

In [105]:
st_patricks = (nyc_crime.start_month == 3) & (nyc_crime.start_day == 17)

In [106]:
nyc_crime['st_patricks'] = st_patricks.astype(int)

The following section uses boolean masks and variable assignment to create new binary columns for major holidays that do not fall on the same day every year. The first step creates separate boolean masks for the date of the holiday in question for each year, then a boolean mask is created for all years based on the boolean masks for each individual year, and then the holiday's column variable is created. To keep the dataset tidy, the variables for each holiday's year are then deleted from the DataFrame.

For this section, I plan on going back to create dictionary comprehensions using lists of values to code the irregularly dated holidays more efficiently and Pythonically.

In [107]:
#Martin Luther King Day
mlk06 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2006) 
mlk07 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2007)
mlk08 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 21) & (nyc_crime.start_year == 2008)
mlk09 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2009)
mlk10 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 18) & (nyc_crime.start_year == 2010)
mlk11 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 17) & (nyc_crime.start_year == 2011)
mlk12 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2012)
mlk13 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 21) & (nyc_crime.start_year == 2013)
mlk14 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 20) & (nyc_crime.start_year == 2014)
mlk15 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2015)
mlk16 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 18) & (nyc_crime.start_year == 2016)
mlk17 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2017)
mlk18 = (nyc_crime.start_month == 1) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2018)

In [108]:
nyc_crime['mlk06'] = mlk06.astype(int)
nyc_crime['mlk07'] = mlk07.astype(int)
nyc_crime['mlk08'] = mlk08.astype(int)
nyc_crime['mlk09'] = mlk09.astype(int)
nyc_crime['mlk10'] = mlk10.astype(int)
nyc_crime['mlk11'] = mlk11.astype(int)
nyc_crime['mlk12'] = mlk12.astype(int)
nyc_crime['mlk13'] = mlk13.astype(int)
nyc_crime['mlk14'] = mlk14.astype(int)
nyc_crime['mlk15'] = mlk15.astype(int)
nyc_crime['mlk16'] = mlk16.astype(int)
nyc_crime['mlk17'] = mlk17.astype(int)
nyc_crime['mlk18'] = mlk18.astype(int)

In [109]:
mlk = (nyc_crime.mlk06 == 1) | (nyc_crime.mlk07 == 1) | (nyc_crime.mlk08 == 1) | (nyc_crime.mlk09 == 1) | (nyc_crime.mlk10 == 1) | (nyc_crime.mlk11 == 1) | (nyc_crime.mlk12 == 1) | (nyc_crime.mlk13 == 1) | (nyc_crime.mlk14 == 1) | (nyc_crime.mlk15 == 1) | (nyc_crime.mlk16 == 1) | (nyc_crime.mlk17 == 1) | (nyc_crime.mlk18 == 1)

In [110]:
nyc_crime['mlk'] = mlk.astype(int)

In [111]:
nyc_crime.mlk.value_counts()

0    6468837
1      14687
Name: mlk, dtype: int64

In [112]:
nyc_crime = nyc_crime.drop(columns=['mlk06', 'mlk07', 'mlk08', 'mlk09', 'mlk10', 'mlk11', 'mlk12', 'mlk13', 'mlk14', 'mlk15', 'mlk16', 'mlk17', 'mlk18'])

In [113]:
#President's Day
pres06 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2006)
pres07 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2007)
pres08 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 18) & (nyc_crime.start_year == 2008)
pres09 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2009)
pres10 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2010)
pres11 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 21) & (nyc_crime.start_year == 2011)
pres12 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 20) & (nyc_crime.start_year == 2012)
pres13 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 18) & (nyc_crime.start_year == 2013)
pres14 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 17) & (nyc_crime.start_year == 2014)
pres15 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2015)
pres16 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2016)
pres17 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 20) & (nyc_crime.start_year == 2017)
pres18 = (nyc_crime.start_month == 2) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2018)

In [114]:
nyc_crime['pres06'] = pres06.astype(int)
nyc_crime['pres07'] = pres07.astype(int)
nyc_crime['pres08'] = pres08.astype(int)
nyc_crime['pres09'] = pres09.astype(int)
nyc_crime['pres10'] = pres10.astype(int)
nyc_crime['pres11'] = pres11.astype(int)
nyc_crime['pres12'] = pres12.astype(int)
nyc_crime['pres13'] = pres13.astype(int)
nyc_crime['pres14'] = pres14.astype(int)
nyc_crime['pres15'] = pres15.astype(int)
nyc_crime['pres16'] = pres16.astype(int)
nyc_crime['pres17'] = pres17.astype(int)
nyc_crime['pres18'] = pres18.astype(int)

In [115]:
pres = (nyc_crime.pres06 == 1) | (nyc_crime.pres07 == 1) | (nyc_crime.pres08 == 1) | (nyc_crime.pres09 == 1) | (nyc_crime.pres10 == 1) | (nyc_crime.pres11 == 1) | (nyc_crime.pres12 == 1) | (nyc_crime.pres13 == 1) | (nyc_crime.pres14 == 1) | (nyc_crime.pres15 == 1) | (nyc_crime.pres16 == 1) | (nyc_crime.pres17 == 1) | (nyc_crime.pres18 == 1)

In [116]:
nyc_crime['pres'] = pres.astype(int)

In [117]:
nyc_crime.pres.value_counts()

0    6469189
1      14335
Name: pres, dtype: int64

In [118]:
nyc_crime = nyc_crime.drop(columns = ['pres06', 'pres07', 'pres08', 'pres09', 'pres10', 'pres11', 'pres12', 'pres13', 'pres14', 'pres15', 'pres16', 'pres17', 'pres18'])

In [119]:
#Easter
easter06 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2006)
easter07 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 8) & (nyc_crime.start_year == 2007)
easter08 = (nyc_crime.start_month == 3) & (nyc_crime.start_day == 23) & (nyc_crime.start_year == 2008)
easter09 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 12) & (nyc_crime.start_year == 2009)
easter10 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 4) & (nyc_crime.start_year == 2010)
easter11 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2011)
easter12 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 8) & (nyc_crime.start_year == 2012)
easter13 = (nyc_crime.start_month == 3) & (nyc_crime.start_day == 31) & (nyc_crime.start_year == 2013)
easter14 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 20) & (nyc_crime.start_year == 2014)
easter15 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 5) & (nyc_crime.start_year == 2015)
easter16 = (nyc_crime.start_month == 3) & (nyc_crime.start_day == 27) & (nyc_crime.start_year == 2016)
easter17 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2017)
easter18 = (nyc_crime.start_month == 4) & (nyc_crime.start_day == 1) & (nyc_crime.start_year == 2018)

In [120]:
nyc_crime['easter06'] = easter06.astype(int)
nyc_crime['easter07'] = easter07.astype(int)
nyc_crime['easter08'] = easter08.astype(int)
nyc_crime['easter09'] = easter09.astype(int)
nyc_crime['easter10'] = easter10.astype(int)
nyc_crime['easter11'] = easter11.astype(int)
nyc_crime['easter12'] = easter12.astype(int)
nyc_crime['easter13'] = easter13.astype(int)
nyc_crime['easter14'] = easter14.astype(int)
nyc_crime['easter15'] = easter15.astype(int)
nyc_crime['easter16'] = easter16.astype(int)
nyc_crime['easter17'] = easter17.astype(int)
nyc_crime['easter18'] = easter18.astype(int)

In [121]:
easter = (nyc_crime.easter06 == 1) | (nyc_crime.easter07 == 1) | (nyc_crime.easter08 == 1) | (nyc_crime.easter09 == 1) | (nyc_crime.easter10 == 1) | (nyc_crime.easter11 == 1) | (nyc_crime.easter12 == 1) | (nyc_crime.easter13 == 1) | (nyc_crime.easter14 == 1) | (nyc_crime.easter15 == 1) | (nyc_crime.easter16 == 1) | (nyc_crime.easter17 == 1) | (nyc_crime.easter18 == 1)

In [122]:
nyc_crime['easter'] = easter.astype(int)

In [123]:
nyc_crime.easter.value_counts()

0    6469307
1      14217
Name: easter, dtype: int64

In [124]:
nyc_crime = nyc_crime.drop(columns = ['easter06', 'easter07', 'easter08', 'easter09', 'easter10', 'easter11', 'easter12', 'easter13', 'easter14', 'easter15', 'easter16', 'easter17', 'easter18'])

In [125]:
#Diwali
diwali06 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 21) & (nyc_crime.start_year == 2006)
diwali07 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 9) & (nyc_crime.start_year == 2007)
diwali08 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2008)
diwali09 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 17) & (nyc_crime.start_year == 2009)
diwali10 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 5) & (nyc_crime.start_year == 2010)
diwali11 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2011)
diwali12 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 13) & (nyc_crime.start_year == 2012)
diwali13 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 3) & (nyc_crime.start_year == 2013)
diwali14 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 23) & (nyc_crime.start_year == 2014)
diwali15 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 11) & (nyc_crime.start_year == 2015)
diwali16 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 30) & (nyc_crime.start_year == 2016)
diwali17 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2017)
diwali18 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 7) & (nyc_crime.start_year == 2018)

In [126]:
nyc_crime['diwali06'] = diwali06.astype(int)
nyc_crime['diwali07'] = diwali07.astype(int)
nyc_crime['diwali08'] = diwali08.astype(int)
nyc_crime['diwali09'] = diwali09.astype(int)
nyc_crime['diwali10'] = diwali10.astype(int)
nyc_crime['diwali11'] = diwali11.astype(int)
nyc_crime['diwali12'] = diwali12.astype(int)
nyc_crime['diwali13'] = diwali13.astype(int)
nyc_crime['diwali14'] = diwali14.astype(int)
nyc_crime['diwali15'] = diwali15.astype(int)
nyc_crime['diwali16'] = diwali16.astype(int)
nyc_crime['diwali17'] = diwali17.astype(int)
nyc_crime['diwali18'] = diwali18.astype(int)

In [127]:
diwali = (nyc_crime.diwali06 == 1) | (nyc_crime.diwali07 == 1) | (nyc_crime.diwali08 == 1) | (nyc_crime.diwali09 == 1) | (nyc_crime.diwali10 == 1) | (nyc_crime.diwali11 == 1) | (nyc_crime.diwali12 == 1) | (nyc_crime.diwali13 == 1) | (nyc_crime.diwali14 == 1) | (nyc_crime.diwali15 == 1) | (nyc_crime.diwali16 == 1) | (nyc_crime.diwali17 == 1) | (nyc_crime.diwali18 == 1)

In [128]:
nyc_crime['diwali'] = diwali.astype(int)

In [129]:
nyc_crime.diwali.value_counts()

0    6465951
1      17573
Name: diwali, dtype: int64

In [130]:
nyc_crime = nyc_crime.drop(columns = ['diwali06', 'diwali07', 'diwali08', 'diwali09', 'diwali10', 'diwali11', 'diwali12', 'diwali13', 'diwali14', 'diwali15', 'diwali16', 'diwali17', 'diwali18'])

In [131]:
#Puerto Rican Day Parade
pr_parade06 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 11) & (nyc_crime.start_year == 2006)
pr_parade07 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 10) & (nyc_crime.start_year == 2007)
pr_parade08 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 8) & (nyc_crime.start_year == 2008)
pr_parade09 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 14) & (nyc_crime.start_year == 2009)
pr_parade10 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 13) & (nyc_crime.start_year == 2010)
pr_parade11 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 12) & (nyc_crime.start_year == 2011)
pr_parade12 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 10) & (nyc_crime.start_year == 2012)
pr_parade13 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 9) & (nyc_crime.start_year == 2013)
pr_parade14 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 8) & (nyc_crime.start_year == 2014)
pr_parade15 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 14) & (nyc_crime.start_year == 2015)
pr_parade16 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 12) & (nyc_crime.start_year == 2016)
pr_parade17 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 11) & (nyc_crime.start_year == 2017)
pr_parade18 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 10) & (nyc_crime.start_year == 2018)

In [132]:
nyc_crime['pr_parade06'] = pr_parade06.astype(int)
nyc_crime['pr_parade07'] = pr_parade07.astype(int)
nyc_crime['pr_parade08'] = pr_parade08.astype(int)
nyc_crime['pr_parade09'] = pr_parade09.astype(int)
nyc_crime['pr_parade10'] = pr_parade10.astype(int)
nyc_crime['pr_parade11'] = pr_parade11.astype(int)
nyc_crime['pr_parade12'] = pr_parade12.astype(int)
nyc_crime['pr_parade13'] = pr_parade13.astype(int)
nyc_crime['pr_parade14'] = pr_parade14.astype(int)
nyc_crime['pr_parade15'] = pr_parade15.astype(int)
nyc_crime['pr_parade16'] = pr_parade16.astype(int)
nyc_crime['pr_parade17'] = pr_parade17.astype(int)
nyc_crime['pr_parade18'] = pr_parade18.astype(int)

In [133]:
pr_parade = (nyc_crime.pr_parade06 == 1) | (nyc_crime.pr_parade07 == 1) | (nyc_crime.pr_parade08 == 1) | (nyc_crime.pr_parade09 == 1) | (nyc_crime.pr_parade10 == 1) | (nyc_crime.pr_parade11 == 1) | (nyc_crime.pr_parade12 == 1) | (nyc_crime.pr_parade13 == 1) | (nyc_crime.pr_parade14 == 1) | (nyc_crime.pr_parade15 == 1) | (nyc_crime.pr_parade16 == 1) | (nyc_crime.pr_parade17 == 1) | (nyc_crime.pr_parade18 == 1)

In [134]:
nyc_crime['pr_parade'] = pr_parade.astype(int)

In [135]:
nyc_crime.pr_parade.value_counts()

0    6466451
1      17073
Name: pr_parade, dtype: int64

In [136]:
nyc_crime = nyc_crime.drop(columns = ['pr_parade06', 'pr_parade07', 'pr_parade08', 'pr_parade09', 'pr_parade10', 'pr_parade11', 'pr_parade12', 'pr_parade13', 'pr_parade14', 'pr_parade15', 'pr_parade16', 'pr_parade17', 'pr_parade18'])

In [137]:
#Yom Kippur
yomkippur06 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 2) & (nyc_crime.start_year == 2006)
yomkippur07 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2007)
yomkippur08 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 9) & (nyc_crime.start_year == 2008)
yomkippur09 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2009)
yomkippur10 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 18) & (nyc_crime.start_year == 2010)
yomkippur11 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 8) & (nyc_crime.start_year == 2011)
yomkippur12 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2012)
yomkippur13 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 14) & (nyc_crime.start_year == 2013)
yomkippur14 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 4) & (nyc_crime.start_year == 2014)
yomkippur15 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 23) & (nyc_crime.start_year == 2015)
yomkippur16 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 12) & (nyc_crime.start_year == 2016)
yomkippur17 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 30) & (nyc_crime.start_year == 2017)
yomkippur18 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2018)

In [138]:
nyc_crime['yomkippur06'] = yomkippur06.astype(int)
nyc_crime['yomkippur07'] = yomkippur07.astype(int)
nyc_crime['yomkippur08'] = yomkippur08.astype(int)
nyc_crime['yomkippur09'] = yomkippur09.astype(int)
nyc_crime['yomkippur10'] = yomkippur10.astype(int)
nyc_crime['yomkippur11'] = yomkippur11.astype(int)
nyc_crime['yomkippur12'] = yomkippur12.astype(int)
nyc_crime['yomkippur13'] = yomkippur13.astype(int)
nyc_crime['yomkippur14'] = yomkippur14.astype(int)
nyc_crime['yomkippur15'] = yomkippur15.astype(int)
nyc_crime['yomkippur16'] = yomkippur16.astype(int)
nyc_crime['yomkippur17'] = yomkippur17.astype(int)
nyc_crime['yomkippur18'] = yomkippur18.astype(int)

In [139]:
yomkippur = (nyc_crime.yomkippur06 == 1) | (nyc_crime.yomkippur07 == 1) | (nyc_crime.yomkippur08 == 1) | (nyc_crime.yomkippur09 == 1) | (nyc_crime.yomkippur10 == 1) | (nyc_crime.yomkippur11 == 1) | (nyc_crime.yomkippur12 == 1) | (nyc_crime.yomkippur13 == 1) | (nyc_crime.yomkippur14 == 1) | (nyc_crime.yomkippur15 == 1) | (nyc_crime.yomkippur16 == 1) | (nyc_crime.yomkippur17 == 1) | (nyc_crime.yomkippur18 == 1)

In [140]:
nyc_crime['yomkippur'] = yomkippur.astype(int)

In [141]:
nyc_crime.yomkippur.value_counts()

0    6465319
1      18205
Name: yomkippur, dtype: int64

In [142]:
nyc_crime = nyc_crime.drop(columns = ['yomkippur06', 'yomkippur07', 'yomkippur08', 'yomkippur09', 'yomkippur10', 'yomkippur11', 'yomkippur12', 'yomkippur13', 'yomkippur14', 'yomkippur15', 'yomkippur16', 'yomkippur17', 'yomkippur18'])

In [143]:
#Rosh Hashanah
rosh_hashanah06 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2006)
rosh_hashanah07 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 14) & (nyc_crime.start_year == 2007)
rosh_hashanah08 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 1) & (nyc_crime.start_year == 2008)
rosh_hashanah09 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 20) & (nyc_crime.start_year == 2009)
rosh_hashanah10 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 10) & (nyc_crime.start_year == 2010)
rosh_hashanah11 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 30) & (nyc_crime.start_year == 2011)
rosh_hashanah12 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 18) & (nyc_crime.start_year == 2012)
rosh_hashanah13 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 6) & (nyc_crime.start_year == 2013)
rosh_hashanah14 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2014)
rosh_hashanah15 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2015)
rosh_hashanah16 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 4) & (nyc_crime.start_year == 2016)
rosh_hashanah17 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2017)
rosh_hashanah18 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 11) & (nyc_crime.start_year == 2018)

In [144]:
nyc_crime['rosh_hashanah06'] = rosh_hashanah06.astype(int)
nyc_crime['rosh_hashanah07'] = rosh_hashanah07.astype(int)
nyc_crime['rosh_hashanah08'] = rosh_hashanah08.astype(int)
nyc_crime['rosh_hashanah09'] = rosh_hashanah09.astype(int)
nyc_crime['rosh_hashanah10'] = rosh_hashanah10.astype(int)
nyc_crime['rosh_hashanah11'] = rosh_hashanah11.astype(int)
nyc_crime['rosh_hashanah12'] = rosh_hashanah12.astype(int)
nyc_crime['rosh_hashanah13'] = rosh_hashanah13.astype(int)
nyc_crime['rosh_hashanah14'] = rosh_hashanah14.astype(int)
nyc_crime['rosh_hashanah15'] = rosh_hashanah15.astype(int)
nyc_crime['rosh_hashanah16'] = rosh_hashanah16.astype(int)
nyc_crime['rosh_hashanah17'] = rosh_hashanah17.astype(int)
nyc_crime['rosh_hashanah18'] = rosh_hashanah18.astype(int)

In [145]:
rosh_hashanah = (nyc_crime.rosh_hashanah06 == 1) | (nyc_crime.rosh_hashanah07 == 1) | (nyc_crime.rosh_hashanah08 == 1) | (nyc_crime.rosh_hashanah09 == 1) | (nyc_crime.rosh_hashanah10 == 1) | (nyc_crime.rosh_hashanah11 == 1) | (nyc_crime.rosh_hashanah12 == 1) | (nyc_crime.rosh_hashanah13 == 1) | (nyc_crime.rosh_hashanah14 == 1) | (nyc_crime.rosh_hashanah15 == 1) | (nyc_crime.rosh_hashanah16 == 1) | (nyc_crime.rosh_hashanah17 == 1) | (nyc_crime.rosh_hashanah18 == 1)

In [146]:
nyc_crime['rosh_hashanah'] = rosh_hashanah.astype(int)

In [147]:
nyc_crime.rosh_hashanah.value_counts()

0    6464763
1      18761
Name: rosh_hashanah, dtype: int64

In [148]:
nyc_crime = nyc_crime.drop(columns = ['rosh_hashanah06', 'rosh_hashanah07', 'rosh_hashanah08', 'rosh_hashanah09', 'rosh_hashanah10', 'rosh_hashanah11', 'rosh_hashanah12', 'rosh_hashanah13', 'rosh_hashanah14', 'rosh_hashanah15', 'rosh_hashanah16', 'rosh_hashanah17', 'rosh_hashanah18'])

In [149]:
#Eid al-Fitr
eid_al_fitr06 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2006)
eid_al_fitr07 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 13) & (nyc_crime.start_year == 2007)
eid_al_fitr08 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 2) & (nyc_crime.start_year == 2008)
eid_al_fitr09 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 21) & (nyc_crime.start_year == 2009)
eid_al_fitr10 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 10) & (nyc_crime.start_year == 2010)
eid_al_fitr11 = (nyc_crime.start_month == 8) & (nyc_crime.start_day == 31) & (nyc_crime.start_year == 2011)
eid_al_fitr12 = (nyc_crime.start_month == 8) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2012)
eid_al_fitr13 = (nyc_crime.start_month == 8) & (nyc_crime.start_day == 8) & (nyc_crime.start_year == 2013)
eid_al_fitr14 = (nyc_crime.start_month == 7) & (nyc_crime.start_day == 29) & (nyc_crime.start_year == 2014)
eid_al_fitr15 = (nyc_crime.start_month == 7) & (nyc_crime.start_day == 17) & (nyc_crime.start_year == 2015)
eid_al_fitr16 = (nyc_crime.start_month == 7) & (nyc_crime.start_day == 6) & (nyc_crime.start_year == 2016)
eid_al_fitr17 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 25) & (nyc_crime.start_year == 2017)
eid_al_fitr18 = (nyc_crime.start_month == 6) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2018)

In [150]:
nyc_crime['eid_al_fitr06'] = eid_al_fitr06.astype(int)
nyc_crime['eid_al_fitr07'] = eid_al_fitr07.astype(int)
nyc_crime['eid_al_fitr08'] = eid_al_fitr08.astype(int)
nyc_crime['eid_al_fitr09'] = eid_al_fitr09.astype(int)
nyc_crime['eid_al_fitr10'] = eid_al_fitr10.astype(int)
nyc_crime['eid_al_fitr11'] = eid_al_fitr11.astype(int)
nyc_crime['eid_al_fitr12'] = eid_al_fitr12.astype(int)
nyc_crime['eid_al_fitr13'] = eid_al_fitr13.astype(int)
nyc_crime['eid_al_fitr14'] = eid_al_fitr14.astype(int)
nyc_crime['eid_al_fitr15'] = eid_al_fitr15.astype(int)
nyc_crime['eid_al_fitr16'] = eid_al_fitr16.astype(int)
nyc_crime['eid_al_fitr17'] = eid_al_fitr17.astype(int)
nyc_crime['eid_al_fitr18'] = eid_al_fitr18.astype(int)

In [151]:
eid_al_fitr = (nyc_crime.eid_al_fitr06 == 1) | (nyc_crime.eid_al_fitr07 == 1) | (nyc_crime.eid_al_fitr08 == 1) | (nyc_crime.eid_al_fitr09 == 1) | (nyc_crime.eid_al_fitr10 == 1) | (nyc_crime.eid_al_fitr11 == 1) | (nyc_crime.eid_al_fitr12 == 1) | (nyc_crime.eid_al_fitr13 == 1) | (nyc_crime.eid_al_fitr14 == 1) | (nyc_crime.eid_al_fitr15 == 1) | (nyc_crime.eid_al_fitr16 == 1) | (nyc_crime.eid_al_fitr17 == 1) | (nyc_crime.eid_al_fitr18 == 1)

In [152]:
nyc_crime['eid_al_fitr'] = eid_al_fitr.astype(int)

In [153]:
nyc_crime.eid_al_fitr.value_counts()

0    6464902
1      18622
Name: eid_al_fitr, dtype: int64

In [154]:
nyc_crime = nyc_crime.drop(columns = ['eid_al_fitr06', 'eid_al_fitr07', 'eid_al_fitr08', 'eid_al_fitr09', 'eid_al_fitr10', 'eid_al_fitr11', 'eid_al_fitr12', 'eid_al_fitr13', 'eid_al_fitr14', 'eid_al_fitr15', 'eid_al_fitr16', 'eid_al_fitr17', 'eid_al_fitr18'])

In [155]:
#Eid al-Adha
eid_al_adha06 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 31) & (nyc_crime.start_year == 2006)
eid_al_adha07 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2007)
eid_al_adha08 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 9) & (nyc_crime.start_year == 2008)
eid_al_adha09 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 27) & (nyc_crime.start_year == 2009)
eid_al_adha10 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2010)
eid_al_adha11 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 6) & (nyc_crime.start_year == 2011)
eid_al_adha12 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2012)
eid_al_adha13 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 15) & (nyc_crime.start_year == 2013)
eid_al_adha14 = (nyc_crime.start_month == 10) & (nyc_crime.start_day == 4) & (nyc_crime.start_year == 2014)
eid_al_adha15 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2015)
eid_al_adha16 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 12) & (nyc_crime.start_year == 2016)
eid_al_adha17 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 1) & (nyc_crime.start_year == 2017)
eid_al_adha18 = (nyc_crime.start_month == 8) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2018)

In [156]:
nyc_crime['eid_al_adha06'] = eid_al_adha06.astype(int)
nyc_crime['eid_al_adha07'] = eid_al_adha07.astype(int)
nyc_crime['eid_al_adha08'] = eid_al_adha08.astype(int)
nyc_crime['eid_al_adha09'] = eid_al_adha09.astype(int)
nyc_crime['eid_al_adha10'] = eid_al_adha10.astype(int)
nyc_crime['eid_al_adha11'] = eid_al_adha11.astype(int)
nyc_crime['eid_al_adha12'] = eid_al_adha12.astype(int)
nyc_crime['eid_al_adha13'] = eid_al_adha13.astype(int)
nyc_crime['eid_al_adha14'] = eid_al_adha14.astype(int)
nyc_crime['eid_al_adha15'] = eid_al_adha15.astype(int)
nyc_crime['eid_al_adha16'] = eid_al_adha16.astype(int)
nyc_crime['eid_al_adha17'] = eid_al_adha17.astype(int)
nyc_crime['eid_al_adha18'] = eid_al_adha18.astype(int)

In [157]:
eid_al_adha = (nyc_crime.eid_al_adha06 == 1) | (nyc_crime.eid_al_adha07 == 1) | (nyc_crime.eid_al_adha08 == 1) | (nyc_crime.eid_al_adha09 == 1) | (nyc_crime.eid_al_adha10 == 1) | (nyc_crime.eid_al_adha11 == 1) | (nyc_crime.eid_al_adha12 == 1) | (nyc_crime.eid_al_adha13 == 1) | (nyc_crime.eid_al_adha14 == 1) | (nyc_crime.eid_al_adha15 == 1) | (nyc_crime.eid_al_adha16 == 1) | (nyc_crime.eid_al_adha17 == 1) | (nyc_crime.eid_al_adha18 == 1)

In [158]:
nyc_crime['eid_al_adha'] = eid_al_adha.astype(int)

In [159]:
nyc_crime.eid_al_adha.value_counts()

0    6466098
1      17426
Name: eid_al_adha, dtype: int64

In [160]:
nyc_crime = nyc_crime.drop(columns = ['eid_al_adha06', 'eid_al_adha07', 'eid_al_adha08', 'eid_al_adha09', 'eid_al_adha10', 'eid_al_adha11', 'eid_al_adha12', 'eid_al_adha13', 'eid_al_adha14', 'eid_al_adha15', 'eid_al_adha16', 'eid_al_adha17', 'eid_al_adha18'])

In [161]:
#Hannukkah
hannukkah06 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 23) & (nyc_crime.start_year == 2006)
hannukkah07 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 12) & (nyc_crime.start_year == 2007)
hannukkah08 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 29) & (nyc_crime.start_year == 2008)
hannukkah09 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 19) & (nyc_crime.start_year == 2009)
hannukkah10 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 9) & (nyc_crime.start_year == 2010)
hannukkah11 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2011)
hannukkah12 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 16) & (nyc_crime.start_year == 2012)
hannukkah13 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 5) & (nyc_crime.start_year == 2013)
hannukkah14 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2014)
hannukkah15 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 14) & (nyc_crime.start_year == 2015)
hannukkah16 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 31) & (nyc_crime.start_year == 2016)
hannukkah17 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 20) & (nyc_crime.start_year == 2017)
hannukkah18 = (nyc_crime.start_month == 12) & (nyc_crime.start_day == 10) & (nyc_crime.start_year == 2018)

In [162]:
nyc_crime['hannukkah06'] = hannukkah06.astype(int)
nyc_crime['hannukkah07'] = hannukkah07.astype(int)
nyc_crime['hannukkah08'] = hannukkah08.astype(int)
nyc_crime['hannukkah09'] = hannukkah09.astype(int)
nyc_crime['hannukkah10'] = hannukkah10.astype(int)
nyc_crime['hannukkah11'] = hannukkah11.astype(int)
nyc_crime['hannukkah12'] = hannukkah12.astype(int)
nyc_crime['hannukkah13'] = hannukkah13.astype(int)
nyc_crime['hannukkah14'] = hannukkah14.astype(int)
nyc_crime['hannukkah15'] = hannukkah15.astype(int)
nyc_crime['hannukkah16'] = hannukkah16.astype(int)
nyc_crime['hannukkah17'] = hannukkah17.astype(int)
nyc_crime['hannukkah18'] = hannukkah18.astype(int)

In [163]:
hannukkah = (nyc_crime.hannukkah06 == 1) | (nyc_crime.hannukkah07 == 1) | (nyc_crime.hannukkah08 == 1) | (nyc_crime.hannukkah09 == 1) | (nyc_crime.hannukkah10 == 1) | (nyc_crime.hannukkah11 == 1) | (nyc_crime.hannukkah12 == 1) | (nyc_crime.hannukkah13 == 1) | (nyc_crime.hannukkah14 == 1) | (nyc_crime.hannukkah15 == 1) | (nyc_crime.hannukkah16 == 1) | (nyc_crime.hannukkah17 == 1) | (nyc_crime.hannukkah18 == 1)

In [164]:
nyc_crime['hannukkah'] = hannukkah.astype(int)

In [165]:
nyc_crime.hannukkah.value_counts()

0    6467429
1      16095
Name: hannukkah, dtype: int64

In [166]:
nyc_crime = nyc_crime.drop(columns = ['hannukkah06', 'hannukkah07', 'hannukkah08', 'hannukkah09', 'hannukkah10', 'hannukkah11', 'hannukkah12', 'hannukkah13', 'hannukkah14', 'hannukkah15', 'hannukkah16', 'hannukkah17', 'hannukkah18'])

In [167]:
#Memorial Day
memorial_day06 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 29) & (nyc_crime.start_year == 2006)
memorial_day07 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2007)
memorial_day08 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2008)
memorial_day09 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 25) & (nyc_crime.start_year == 2009)
memorial_day10 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 31) & (nyc_crime.start_year == 2010)
memorial_day11 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 30) & (nyc_crime.start_year == 2011)
memorial_day12 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2012)
memorial_day13 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 27) & (nyc_crime.start_year == 2013)
memorial_day14 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2014)
memorial_day15 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 25) & (nyc_crime.start_year == 2015)
memorial_day16 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 30) & (nyc_crime.start_year == 2016)
memorial_day17 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 29) & (nyc_crime.start_year == 2017)
memorial_day18 = (nyc_crime.start_month == 5) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2018)

In [168]:
nyc_crime['memorial_day06'] = memorial_day06.astype(int)
nyc_crime['memorial_day07'] = memorial_day07.astype(int)
nyc_crime['memorial_day08'] = memorial_day08.astype(int)
nyc_crime['memorial_day09'] = memorial_day09.astype(int)
nyc_crime['memorial_day10'] = memorial_day10.astype(int)
nyc_crime['memorial_day11'] = memorial_day11.astype(int)
nyc_crime['memorial_day12'] = memorial_day12.astype(int)
nyc_crime['memorial_day13'] = memorial_day13.astype(int)
nyc_crime['memorial_day14'] = memorial_day14.astype(int)
nyc_crime['memorial_day15'] = memorial_day15.astype(int)
nyc_crime['memorial_day16'] = memorial_day16.astype(int)
nyc_crime['memorial_day17'] = memorial_day17.astype(int)
nyc_crime['memorial_day18'] = memorial_day18.astype(int)

In [169]:
memorial_day = (nyc_crime.memorial_day06 == 1) | (nyc_crime.memorial_day07 == 1) | (nyc_crime.memorial_day08 == 1) | (nyc_crime.memorial_day09 == 1) | (nyc_crime.memorial_day10 == 1) | (nyc_crime.memorial_day11 == 1) | (nyc_crime.memorial_day12 == 1) | (nyc_crime.memorial_day13 == 1) | (nyc_crime.memorial_day14 == 1) | (nyc_crime.memorial_day15 == 1) | (nyc_crime.memorial_day16 == 1) | (nyc_crime.memorial_day17 == 1) | (nyc_crime.memorial_day18 == 1)

In [170]:
nyc_crime['memorial_day'] = memorial_day.astype(int)

In [171]:
nyc_crime.memorial_day.value_counts()

0    6467488
1      16036
Name: memorial_day, dtype: int64

In [172]:
nyc_crime = nyc_crime.drop(columns = ['memorial_day06', 'memorial_day07', 'memorial_day08', 'memorial_day09', 'memorial_day10', 'memorial_day11', 'memorial_day12', 'memorial_day13', 'memorial_day14', 'memorial_day15', 'memorial_day16', 'memorial_day17', 'memorial_day18'])

In [173]:
labor_day06 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 4) & (nyc_crime.start_year == 2006)
labor_day07 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 3) & (nyc_crime.start_year == 2007)
labor_day08 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 1) & (nyc_crime.start_year == 2008)
labor_day09 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 7) & (nyc_crime.start_year == 2009)
labor_day10 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 6) & (nyc_crime.start_year == 2010)
labor_day11 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 5) & (nyc_crime.start_year == 2011)
labor_day12 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 3) & (nyc_crime.start_year == 2012)
labor_day13 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 2) & (nyc_crime.start_year == 2013)
labor_day14 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 1) & (nyc_crime.start_year == 2014)
labor_day15 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 7) & (nyc_crime.start_year == 2015)
labor_day16 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 5) & (nyc_crime.start_year == 2016)
labor_day17 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 4) & (nyc_crime.start_year == 2017)
labor_day18 = (nyc_crime.start_month == 9) & (nyc_crime.start_day == 3) & (nyc_crime.start_year == 2018)

In [174]:
nyc_crime['labor_day06'] = labor_day06.astype(int)
nyc_crime['labor_day07'] = labor_day07.astype(int)
nyc_crime['labor_day08'] = labor_day08.astype(int)
nyc_crime['labor_day09'] = labor_day09.astype(int)
nyc_crime['labor_day10'] = labor_day10.astype(int)
nyc_crime['labor_day11'] = labor_day11.astype(int)
nyc_crime['labor_day12'] = labor_day12.astype(int)
nyc_crime['labor_day13'] = labor_day13.astype(int)
nyc_crime['labor_day14'] = labor_day14.astype(int)
nyc_crime['labor_day15'] = labor_day15.astype(int)
nyc_crime['labor_day16'] = labor_day16.astype(int)
nyc_crime['labor_day17'] = labor_day17.astype(int)
nyc_crime['labor_day18'] = labor_day18.astype(int)

In [175]:
labor_day = (nyc_crime.labor_day06 == 1) | (nyc_crime.labor_day07 == 1) | (nyc_crime.labor_day08 == 1) | (nyc_crime.labor_day09 == 1) | (nyc_crime.labor_day10 == 1) | (nyc_crime.labor_day11 == 1) | (nyc_crime.labor_day12 == 1) | (nyc_crime.labor_day13 == 1) | (nyc_crime.labor_day14 == 1) | (nyc_crime.labor_day15 == 1) | (nyc_crime.labor_day16 == 1) | (nyc_crime.labor_day17 == 1) | (nyc_crime.labor_day18 == 1)

In [176]:
nyc_crime['labor_day'] = labor_day.astype(int)

In [177]:
nyc_crime.labor_day.value_counts()

0    6465831
1      17693
Name: labor_day, dtype: int64

In [178]:
nyc_crime = nyc_crime.drop(columns = ['labor_day06', 'labor_day07', 'labor_day08', 'labor_day09', 'labor_day10', 'labor_day11', 'labor_day12', 'labor_day13', 'labor_day14', 'labor_day15', 'labor_day16', 'labor_day17', 'labor_day18'])

In [179]:
#Thanksgiving
thanksgiving06 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 23) & (nyc_crime.start_year == 2006)
thanksgiving07 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2007)
thanksgiving08 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 27) & (nyc_crime.start_year == 2008)
thanksgiving09 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2009)
thanksgiving10 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 25) & (nyc_crime.start_year == 2010)
thanksgiving11 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2011)
thanksgiving12 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2012)
thanksgiving13 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 28) & (nyc_crime.start_year == 2013)
thanksgiving14 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 27) & (nyc_crime.start_year == 2014)
thanksgiving15 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 26) & (nyc_crime.start_year == 2015)
thanksgiving16 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 24) & (nyc_crime.start_year == 2016)
thanksgiving17 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 23) & (nyc_crime.start_year == 2017)
thanksgiving18 = (nyc_crime.start_month == 11) & (nyc_crime.start_day == 22) & (nyc_crime.start_year == 2018)

In [180]:
nyc_crime['thanksgiving06'] = thanksgiving06.astype(int)
nyc_crime['thanksgiving07'] = thanksgiving07.astype(int)
nyc_crime['thanksgiving08'] = thanksgiving08.astype(int)
nyc_crime['thanksgiving09'] = thanksgiving09.astype(int)
nyc_crime['thanksgiving10'] = thanksgiving10.astype(int)
nyc_crime['thanksgiving11'] = thanksgiving11.astype(int)
nyc_crime['thanksgiving12'] = thanksgiving12.astype(int)
nyc_crime['thanksgiving13'] = thanksgiving13.astype(int)
nyc_crime['thanksgiving14'] = thanksgiving14.astype(int)
nyc_crime['thanksgiving15'] = thanksgiving15.astype(int)
nyc_crime['thanksgiving16'] = thanksgiving16.astype(int)
nyc_crime['thanksgiving17'] = thanksgiving17.astype(int)
nyc_crime['thanksgiving18'] = thanksgiving18.astype(int)

In [181]:
thanksgiving = (nyc_crime.thanksgiving06 == 1) | (nyc_crime.thanksgiving07 == 1) | (nyc_crime.thanksgiving08 == 1) | (nyc_crime.thanksgiving09 == 1) | (nyc_crime.thanksgiving10 == 1) | (nyc_crime.thanksgiving11 == 1) | (nyc_crime.thanksgiving12 == 1) | (nyc_crime.thanksgiving13 == 1) | (nyc_crime.thanksgiving14 == 1) | (nyc_crime.thanksgiving15 == 1) | (nyc_crime.thanksgiving16 == 1) | (nyc_crime.thanksgiving17 == 1) | (nyc_crime.thanksgiving18 == 1)

In [182]:
nyc_crime['thanksgiving'] = thanksgiving.astype(int)

In [183]:
nyc_crime.thanksgiving.value_counts()

0    6471842
1      11682
Name: thanksgiving, dtype: int64

In [184]:
nyc_crime = nyc_crime.drop(columns = ['thanksgiving06', 'thanksgiving07', 'thanksgiving08', 'thanksgiving09', 'thanksgiving10', 'thanksgiving11', 'thanksgiving12', 'thanksgiving13', 'thanksgiving14', 'thanksgiving15', 'thanksgiving16', 'thanksgiving17', 'thanksgiving18'])

The next part drops cases outside of the stated year range of the dataset, that is, less than 2006

The following code creates a boolean series for years to keep by identifying the years before 2006, and then using this series to create a new column for years to keep.  The cases with a value of zero for the 'years_to_keep' variable are dropped.

In [185]:
years_to_keep = (nyc_crime.start_year > 2005)

In [186]:
nyc_crime['years_to_keep'] = years_to_keep.astype(int)

In [187]:
nyc_crime.years_to_keep.value_counts()

1    6463881
0      19643
Name: years_to_keep, dtype: int64

In [188]:
nyc_crime.drop(nyc_crime[nyc_crime.years_to_keep == 0].index, inplace=True)

In [189]:
nyc_crime['years_to_keep'].value_counts()

1    6463881
Name: years_to_keep, dtype: int64

The 'years_to_keep' column is dropped from the DataFrame, as it is no longer needed.

In [190]:
nyc_crime = nyc_crime.drop(columns = ['years_to_keep'])

Value counts are examined for the 'start_year' variable to make sure all cases before 2006 are dropped.

In [191]:
nyc_crime['start_year'].value_counts()

2007.0    535094
2008.0    528715
2006.0    512620
2009.0    511044
2010.0    510070
2012.0    504652
2011.0    498586
2013.0    495704
2014.0    491842
2015.0    478333
2016.0    477599
2017.0    466664
2018.0    452958
Name: start_year, dtype: int64

The next section recodes unclear values to 'unknown' for the suspect and victim age group, race, and sex variables. First, the value counts are run for each variable. Then, a cleaned version of the variable is created by mapping unusual values to 'unknown'. And finally value counts are called on the cleaned version of the variable to ensure all unusual values have been mapped to 'unknown'.

In [192]:
nyc_crime['SUSP_AGE_GROUP'].value_counts()

unknown    4560650
25-44       795100
UNKNOWN     394066
18-24       318148
45-64       283254
<18          89875
65+          22629
2018            10
2017             8
2016             8
926              4
-972             4
940              4
-969             4
-2               4
-974             3
2015             3
1017             3
-979             3
1018             3
931              3
935              3
936              2
938              2
-1               2
-970             2
-960             2
937              2
-948             2
-962             2
928              2
1016             2
-971             2
-975             2
945              2
922              2
1007             2
-978             2
-976             2
952              2
-980             1
-49              1
927              1
708              1
-42              1
-54              1
946              1
924              1
1014             1
-935             1
-968             1
-963             1
914         

In [193]:
nyc_crime['SUSP_AGE_GROUP_cleaned'] = nyc_crime['SUSP_AGE_GROUP'].map({'<18': '<18', '18-24': '18-24', 
                                                                     '25-44': '25-44', '45-64': '45-64', 
                                                                     '65+': '65+', 'unknown': 'unknown', 
                                                                     'UNKNOWN': 'unknown', '2018': 'unknown', '2016': 'unknown', '2017': 'unknown', '-969': 'unknown', '-2': 'unknown', '940': 'unknown', '-972': 'unknown', '926': 'unknown', '-974': 'unknown', '1018': 'unknown', '935': 'unknown', '931': 'unknown', '1017': 'unknown', '-979': 'unknown', '2015': 'unknown', '-978': 'unknown', '-960': 'unknown', '-970': 'unknown', '937': 'unknown', '936': 'unknown', '945': 'unknown', '928': 'unknown', '-976': 'unknown', '1007': 'unknown', '-948': 'unknown', '1016': 'unknown', '-1': 'unknown', '-975': 'unknown', '-971': 'unknown', '-962': 'unknown', '922': 'unknown', '952': 'unknown', '-963': 'unknown', '933': 'unknown', '920': 'unknown', '1014': 'unknown', '1932': 'unknown', '809': 'unknown', '1967': 'unknown', '966': 'unknown', '925': 'unknown', '-935': 'unknown', '954': 'unknown', '914': 'unknown', '915': 'unknown', '324': 'unknown', '327': 'unknown', '944': 'unknown', '708': 'unknown', '808': 'unknown', '-941': 'unknown', '955': 'unknown', '-49': 'unknown', '709': 'unknown', '-985': 'unknown', '-54': 'unknown', '934': 'unknown', '814': 'unknown', '1053': 'unknown', '-968': 'unknown', '-953': 'unknown', '-939': 'unknown', '946': 'unknown', '924': 'unknown', '-83': 'unknown', '938': 'unknown', '972': 'unknown', '948': 'unknown', '-42': 'unknown', '949': 'unknown', '-973': 'unknown', '-63': 'unknown', '810': 'unknown', '-981': 'unknown', '-80': 'unknown', '927': 'unknown', '-955': 'unknown', '-65': 'unknown', '-67': 'unknown', '-980': 'unknown', '942': 'unknown', '923': 'unknown', '309': 'unknown', '1933': 'unknown', '999': 'unknown', '-72': 'unknown', '711': 'unknown', '-965': 'unknown', '1012': 'unknown'})

In [194]:
nyc_crime['SUSP_AGE_GROUP_cleaned'].value_counts()

unknown    4954875
25-44       795100
18-24       318148
45-64       283254
<18          89875
65+          22629
Name: SUSP_AGE_GROUP_cleaned, dtype: int64

In [195]:
nyc_crime['SUSP_RACE'].value_counts()

unknown                           3200949
BLACK                             1219872
UNKNOWN                            843699
WHITE HISPANIC                     555594
WHITE                              364297
BLACK HISPANIC                     167533
ASIAN / PACIFIC ISLANDER           101781
AMERICAN INDIAN/ALASKAN NATIVE      10146
OTHER                                  10
Name: SUSP_RACE, dtype: int64

In [196]:
nyc_crime['SUSP_RACE_cleaned'] = nyc_crime['SUSP_RACE'].map({'BLACK': 'BLACK', 'WHITE HISPANIC': 'WHITE HISPANIC', 
                                              'BLACK HISPANIC': 'BLACK HISPANIC', 'WHITE': 'WHITE',
                                              'ASIAN / PACIFIC ISLANDER': 'ASIAN / PACIFIC ISLANDER', 
                                              'unknown': 'unknown','UNKNOWN': 'unknown', 
                                              'AMERICAN INDIAN/ALASKAN NATIVE': 'AMERICAN INDIAN/ALASKAN NATIVE'})

After discovering that only 15.8% of cannabis crimes have their suspect's race reported, I wanted to see what percentage of non-cannabis crimes have their suspect's race reported. As can be seen below, 38.2% of non-cannabis crimes have their suspect's race reported. This is a large difference, and warrants a hypothesis test in a later section of this project to see if the difference is due to random chance.

In [197]:
nyc_crime['SUSP_RACE_cleaned'].value_counts(normalize=True)

unknown                           0.625732
BLACK                             0.188722
WHITE HISPANIC                    0.085954
WHITE                             0.056359
BLACK HISPANIC                    0.025918
ASIAN / PACIFIC ISLANDER          0.015746
AMERICAN INDIAN/ALASKAN NATIVE    0.001570
Name: SUSP_RACE_cleaned, dtype: float64

In [198]:
nyc_crime['SUSP_SEX'].value_counts()

unknown    3332467
M          1986164
F           638854
U           506396
Name: SUSP_SEX, dtype: int64

In [199]:
nyc_crime['SUSP_SEX_cleaned'] = nyc_crime['SUSP_SEX'].map({'M': 'M', 'F': 'F', 'U': 'unknown', 
                                                         'unknown': 'unknown'})

In [200]:
nyc_crime['SUSP_SEX_cleaned'].value_counts()

unknown    3838863
M          1986164
F           638854
Name: SUSP_SEX_cleaned, dtype: int64

In [201]:
nyc_crime['VIC_AGE_GROUP'].value_counts()

25-44      2097471
unknown    1630034
45-64      1090644
18-24       663763
UNKNOWN     458670
<18         303729
65+         219184
929             10
946              8
-1               8
937              8
938              8
922              7
936              7
-962             6
-2               5
927              5
808              5
-970             5
947              4
932              4
962              4
942              4
812              4
-972             4
924              4
-964             4
931              4
-973             4
-974             4
-978             4
930              4
948              4
-48              3
711              3
934              3
-950             3
949              3
933              3
809              3
-32              3
-966             3
940              3
939              3
960              3
810              3
-956             3
-980             3
958              3
-72              3
954              3
970              3
926         

In [202]:
nyc_crime['VIC_AGE_GROUP_cleaned'] = nyc_crime['VIC_AGE_GROUP'].map({'UNKNOWN': 'unknown', 'unknown': 'unknown', 
                                                                   '<18': '<18', '18-24': '18-24', 
                                                                   '25-44': '25-44', '45-64': '45-64', 
                                                                   '65+': '65+', '929': 'unknown', '1004': 'unknown', '946': 'unknown', '938': 'unknown', '-1': 'unknown', '937': 'unknown', '922': 'unknown', '936': 'unknown', '-962': 'unknown', '927': 'unknown', '-970': 'unknown', '-2': 'unknown', '808': 'unknown', '924': 'unknown', '-974': 'unknown', '947': 'unknown', '812': 'unknown', '962': 'unknown', '-973': 'unknown', '932': 'unknown', '-964': 'unknown', '942': 'unknown', '931': 'unknown', '-972': 'unknown', '930': 'unknown', '-978': 'unknown', '948': 'unknown', '949': 'unknown', '-955': 'unknown', '934': 'unknown', '-966': 'unknown', '940': 'unknown', '958': 'unknown', '926': 'unknown', '-48': 'unknown', '939': 'unknown', '950': 'unknown', '933': 'unknown', '810': 'unknown', '-956': 'unknown', '809': 'unknown', '-72': 'unknown', '951': 'unknown', '960': 'unknown', '954': 'unknown', '970': 'unknown', '-980': 'unknown', '-32': 'unknown', '-950': 'unknown', '928': 'unknown', '711': 'unknown', '-948': 'unknown', '955': 'unknown', '925': 'unknown', '151': 'unknown', '913': 'unknown', '-940': 'unknown', '-957': 'unknown', '941': 'unknown', '-984': 'unknown', '-60': 'unknown', '964': 'unknown', '-3': 'unknown', '-934': 'unknown', '-959': 'unknown', '944': 'unknown', '914': 'unknown', '-975': 'unknown', '-61': 'unknown', '-982': 'unknown', '-976': 'unknown', '-73': 'unknown', '943': 'unknown', '-40': 'unknown', '959': 'unknown', '811': 'unknown', '945': 'unknown', '953': 'unknown', '-49': 'unknown', '923': 'unknown', '956': 'unknown', '957': 'unknown', '-954': 'unknown', '935': 'unknown', '-952': 'unknown', '-958': 'unknown', '-971': 'unknown', '-943': 'unknown', '-55': 'unknown', '508': 'unknown', '-939': 'unknown', '980': 'unknown', '-63': 'unknown', '918': 'unknown', '-968': 'unknown', '160': 'unknown', '1014': 'unknown', '172': 'unknown', '901': 'unknown', '999': 'unknown', '-961': 'unknown', '509': 'unknown', '158': 'unknown', '-953': 'unknown', '917': 'unknown', '-929': 'unknown', '910': 'unknown', '-47': 'unknown', '895': 'unknown', '965': 'unknown', '-967': 'unknown', '-945': 'unknown', '981': 'unknown', '-7': 'unknown', '-70': 'unknown', '-937': 'unknown', '972': 'unknown', '977': 'unknown', '-43': 'unknown', '-85': 'unknown', '-923': 'unknown', '188': 'unknown', '912': 'unknown', '324': 'unknown', '214': 'unknown', '838': 'unknown', '1017': 'unknown', '-938': 'unknown', '-4': 'unknown', '359': 'unknown', '952': 'unknown', '-915': 'unknown', '979': 'unknown', '738': 'unknown', '334': 'unknown', '342': 'unknown', '-946': 'unknown', '343': 'unknown', '-59': 'unknown', '-81': 'unknown', '-884': 'unknown', '1012': 'unknown', '-936': 'unknown', '-969': 'unknown', '507': 'unknown', '-52': 'unknown', '-981': 'unknown', '-37': 'unknown', '154': 'unknown', '260': 'unknown', '-51': 'unknown', '-5': 'unknown', '309': 'unknown', '-983': 'unknown', '707': 'unknown', '-932': 'unknown', '-39': 'unknown', '-67': 'unknown', '-902': 'unknown', '-75': 'unknown', '-76': 'unknown', '623': 'unknown', '806': 'unknown', '-78': 'unknown', '961': 'unknown', '-53': 'unknown', '340': 'unknown', '-947': 'unknown', '-36': 'unknown', '920': 'unknown', '-931': 'unknown', '-65': 'unknown', '908': 'unknown', '185': 'unknown', '-942': 'unknown', '709': 'unknown', '-985': 'unknown', '-45': 'unknown', '152': 'unknown', '909': 'unknown', '311': 'unknown', '911': 'unknown'})

In [203]:
nyc_crime['VIC_AGE_GROUP_cleaned'].value_counts()

25-44      2097471
unknown    2089090
45-64      1090644
18-24       663763
<18         303729
65+         219184
Name: VIC_AGE_GROUP_cleaned, dtype: int64

In [204]:
nyc_crime['VIC_RACE'].value_counts()

UNKNOWN                           2177590
BLACK                             1534485
WHITE                             1121857
WHITE HISPANIC                    1029257
ASIAN / PACIFIC ISLANDER           358158
BLACK HISPANIC                     212930
AMERICAN INDIAN/ALASKAN NATIVE      29270
unknown                               305
OTHER                                  29
Name: VIC_RACE, dtype: int64

In [205]:
nyc_crime['VIC_RACE_cleaned'] = nyc_crime['VIC_RACE'].map({'UNKNOWN': 'unknown', 'BLACK': 'BLACK', 'WHITE HISPANIC': 'WHITE HISPANIC',
                                            'WHITE': 'WHITE', 'BLACK HISPANIC': 'BLACK HISPANIC', 
                                            'ASIAN / PACIFIC ISLANDER': 'ASIAN / PACIFIC ISLANDER', 
                                            'AMERICAN INDIAN/ALASKAN NATIVE': 'AMERICAN INDIAN/ALASKAN NATIVE', 
                                            'unknown': 'unknown', 'OTHER': 'unknown'})

In [206]:
nyc_crime['VIC_RACE_cleaned'].value_counts()

unknown                           2177924
BLACK                             1534485
WHITE                             1121857
WHITE HISPANIC                    1029257
ASIAN / PACIFIC ISLANDER           358158
BLACK HISPANIC                     212930
AMERICAN INDIAN/ALASKAN NATIVE      29270
Name: VIC_RACE_cleaned, dtype: int64

In [207]:
nyc_crime['VIC_SEX'].value_counts()

F          2522209
M          2107583
E          1064241
D           769540
unknown        304
U                4
Name: VIC_SEX, dtype: int64

In [208]:
nyc_crime['VIC_SEX_cleaned'] = nyc_crime['VIC_SEX'].map({'E': 'unknown', 'M': 'M', 'D': 'unknown', 'F': 'F', 
                                                      'unknown': 'unknown', 'U': 'unknown'})

In [209]:
nyc_crime['VIC_SEX_cleaned'].value_counts()

F          2522209
M          2107583
unknown    1834089
Name: VIC_SEX_cleaned, dtype: int64

The old uncleaned suspect and victim age group, race, and sex variables are dropped from the DataFrame as they are not needed. The 'JURISDICTION_CODE' variable is also dropped as it had numerical codes that were not labelled, and therefore meaningless. Also, a jurisdiction code variable with text labels also exists, so the numerical code isn't needed.

In [210]:
nyc_crime = nyc_crime.drop(columns=['SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX', 'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX', 'JURISDICTION_CODE'])

The next set of cells creates a feature labelling crimes as cannabis crimes or non-cannabis crimes, and the type of cannabis crime as well. This needs to be done before the sampling or the filtering, so it carries throughout without repetitive work.

In [211]:
cannabis_crime = (nyc_crime.PD_CD == 566.0) | (nyc_crime.PD_CD == 567.0) | (nyc_crime.PD_CD == 568.0) | (nyc_crime.PD_CD == 569.0) | (nyc_crime.PD_CD == 570.0)

In [212]:
nyc_crime['cannabis_crime'] = cannabis_crime.astype(int)

In [213]:
nyc_crime['cannabis_crime'].value_counts()

0    6243575
1     220306
Name: cannabis_crime, dtype: int64

In [214]:
cann_poss = (nyc_crime.PD_CD == 566.0) | (nyc_crime.PD_CD == 567.0) | (nyc_crime.PD_CD == 568.0)

In [215]:
nyc_crime['possession'] = cann_poss.astype(int)

In [216]:
cann_sales = (nyc_crime.PD_CD == 569.0) | (nyc_crime.PD_CD == 570.0)

In [217]:
nyc_crime['sales'] = cann_sales.astype(int)

In [218]:
misdemeanor = nyc_crime.LAW_CAT_CD == 'MISDEMEANOR'

In [219]:
nyc_crime['misdemeanor'] = misdemeanor.astype(int)

In [220]:
violation = nyc_crime.LAW_CAT_CD == 'VIOLATION'

In [221]:
nyc_crime['violation'] = violation.astype(int)

In [222]:
felony = nyc_crime.LAW_CAT_CD == 'FELONY'

In [223]:
nyc_crime['felony'] = felony.astype(int)

In [224]:
misd_poss = (nyc_crime.misdemeanor == 1) & (nyc_crime.possession == 1)

In [225]:
nyc_crime['misd_poss'] = misd_poss.astype(int)

In [226]:
nyc_crime['misd_poss'].value_counts()

0    6266655
1     197226
Name: misd_poss, dtype: int64

In [227]:
viol_poss = (nyc_crime.violation == 1) & (nyc_crime.possession == 1)

In [228]:
nyc_crime['viol_poss'] = viol_poss.astype(int)

In [229]:
nyc_crime['viol_poss'].value_counts()

0    6457097
1       6784
Name: viol_poss, dtype: int64

In [230]:
felony_poss = (nyc_crime.felony == 1) & (nyc_crime.possession == 1)

In [231]:
nyc_crime['felony_poss'] = felony_poss.astype(int)

In [232]:
nyc_crime['felony_poss'].value_counts()

0    6460126
1       3755
Name: felony_poss, dtype: int64

In [233]:
misd_sales = (nyc_crime.misdemeanor == 1) & (nyc_crime.sales == 1)

In [234]:
nyc_crime['misd_sales'] = misd_sales.astype(int)

In [235]:
nyc_crime['misd_sales'].value_counts()

0    6452455
1      11426
Name: misd_sales, dtype: int64

In [236]:
felony_sales = (nyc_crime.felony == 1) & (nyc_crime.sales == 1)

In [237]:
nyc_crime['felony_sales'] = felony_sales.astype(int)

In [238]:
nyc_crime['felony_sales'].value_counts()

0    6462766
1       1115
Name: felony_sales, dtype: int64

In [239]:
nyc_crime = nyc_crime.drop(columns=['possession', 'sales', 'misdemeanor', 'violation', 'felony'])

In order to conduct hypothesis testing between cannabis crimes and non-cannabis crimes for just those cases with the suspect's race reported, a subsetted DataFrame of nyc_crime is created, called "nyc_crime_race_reported".

In [240]:
nyc_crime_race_reported = nyc_crime[nyc_crime.SUSP_RACE_cleaned != 'unknown']

In [241]:
nyc_crime_race_reported.shape

(2419233, 129)

In [242]:
nyc_crime.shape

(6463881, 129)

The next several code cells sample a DataFrame of NYC crimes generally, for hypothesis testing in section 8. Even though it is large, a 10% sample is taken. The entire cleaned DataFrame is 6,463,881 records, so 646,388 records are sampled.

In [243]:
nyc_crime_sample = nyc_crime.sample(n=646388, random_state=42, axis=0)

In [244]:
nyc_crime_sample.shape

(646388, 129)

Next, PD_CD and LAW_CAT_CD distributions are compared between all non-cannabis crimes and the sample of non-cannabis crimes. This is done to ensure that certain PD_CD and LAW_CAT_CD are not randomly over-represented in the sample.

In [245]:
nyc_crime.PD_CD.value_counts(normalize=True)

101.0      8.701800e-02
638.0      7.911238e-02
639.0      5.252232e-02
333.0      4.664937e-02
637.0      4.514888e-02
338.0      4.312440e-02
254.0      3.567671e-02
321.0      3.291877e-02
109.0      3.101914e-02
567.0      3.051201e-02
259.0      2.832014e-02
438.0      2.011098e-02
258.0      1.873116e-02
511.0      1.818629e-02
397.0      1.679270e-02
441.0      1.624164e-02
339.0      1.542773e-02
221.0      1.441518e-02
113.0      1.412572e-02
905.0      1.370183e-02
782.0      1.314798e-02
198.0      1.199403e-02
205.0      1.053113e-02
739.0      9.983940e-03
421.0      9.730841e-03
916.0      8.836178e-03
729.0      8.484222e-03
793.0      7.995506e-03
419.0      7.915214e-03
223.0      7.614002e-03
405.0      7.316502e-03
267.0      7.292523e-03
349.0      7.271483e-03
269.0      6.760335e-03
357.0      6.264812e-03
749.0      6.242380e-03
343.0      5.963290e-03
175.0      5.494068e-03
439.0      5.419500e-03
386.0      5.148919e-03
750.0      5.059499e-03
759.0      4.690

In [246]:
nyc_crime_sample.PD_CD.value_counts(normalize=True)

101.0      0.086747
638.0      0.079031
639.0      0.052560
333.0      0.046811
637.0      0.045239
338.0      0.043112
254.0      0.035476
321.0      0.033276
109.0      0.030994
567.0      0.030720
259.0      0.028099
438.0      0.020322
511.0      0.018385
258.0      0.018353
397.0      0.017038
441.0      0.016453
339.0      0.015458
221.0      0.014368
113.0      0.014207
905.0      0.013637
782.0      0.013261
198.0      0.011816
205.0      0.010648
739.0      0.009886
421.0      0.009731
916.0      0.008739
729.0      0.008486
419.0      0.007997
793.0      0.007704
223.0      0.007522
405.0      0.007468
267.0      0.007321
349.0      0.007256
269.0      0.006716
357.0      0.006241
749.0      0.006174
343.0      0.005935
175.0      0.005622
439.0      0.005353
386.0      0.005087
750.0      0.005079
759.0      0.004678
213.0      0.004544
503.0      0.003869
106.0      0.003583
117.0      0.003546
718.0      0.003458
490.0      0.003451
705.0      0.003283
114.0      0.003229


In [247]:
nyc_crime.LAW_CAT_CD.value_counts(normalize=True)

MISDEMEANOR    0.567246
FELONY         0.306389
VIOLATION      0.126365
Name: LAW_CAT_CD, dtype: float64

In [248]:
nyc_crime_sample.LAW_CAT_CD.value_counts(normalize=True)

MISDEMEANOR    0.567405
FELONY         0.306183
VIOLATION      0.126412
Name: LAW_CAT_CD, dtype: float64

In [249]:
nyc_crime_race_reported.shape

(2419233, 129)

The next several code cells sample a DataFrame of NYC crimes with suspect race reported. Even though it is large, a 10% sample is taken. The entire cleaned DataFrame is 2,419,233 records, so 241,923 records are sampled.

In [250]:
nyc_crime_race_reported_sample = nyc_crime_race_reported.sample(n=241923, random_state=42, axis=0)

In [251]:
nyc_crime_race_reported_sample.shape

(241923, 129)

Next, PD_CD and LAW_CAT_CD distributions are compared between all non-cannabis crimes and the sample of non-cannabis crimes. This is done to ensure that certain PD_CD and LAW_CAT_CD are not randomly over-represented in the sample.

In [252]:
nyc_crime_race_reported.PD_CD.value_counts(normalize=True)

638.0      1.621072e-01
101.0      1.299065e-01
637.0      9.886853e-02
639.0      9.608376e-02
333.0      4.528501e-02
109.0      4.201786e-02
397.0      2.944694e-02
259.0      2.457804e-02
113.0      2.246952e-02
198.0      2.215661e-02
338.0      2.198713e-02
749.0      1.291566e-02
567.0      1.268708e-02
386.0      1.008460e-02
511.0      9.167782e-03
419.0      8.655636e-03
254.0      8.461773e-03
905.0      7.976495e-03
175.0      7.600756e-03
339.0      7.138626e-03
269.0      6.936083e-03
782.0      6.889374e-03
438.0      6.410296e-03
114.0      6.259009e-03
748.0      6.096147e-03
729.0      6.045718e-03
388.0      5.870869e-03
105.0      5.757197e-03
205.0      5.146673e-03
793.0      4.769694e-03
221.0      4.511347e-03
433.0      4.086832e-03
462.0      3.843780e-03
399.0      3.698280e-03
916.0      3.435386e-03
681.0      3.365943e-03
878.0      3.355196e-03
321.0      3.316754e-03
157.0      3.272938e-03
223.0      3.170840e-03
267.0      2.993511e-03
478.0      2.976

In [253]:
nyc_crime_race_reported_sample.PD_CD.value_counts(normalize=True)

638.0      0.161733
101.0      0.130165
637.0      0.097779
639.0      0.095820
333.0      0.045068
109.0      0.041893
397.0      0.029352
259.0      0.024714
198.0      0.022524
338.0      0.022197
113.0      0.022148
749.0      0.013434
567.0      0.012909
386.0      0.010152
511.0      0.009247
254.0      0.008519
419.0      0.008499
905.0      0.007957
175.0      0.007672
339.0      0.007072
269.0      0.006899
782.0      0.006820
438.0      0.006568
114.0      0.006300
748.0      0.006159
729.0      0.006130
388.0      0.005741
105.0      0.005663
205.0      0.005088
793.0      0.004741
221.0      0.004522
433.0      0.004018
462.0      0.003774
399.0      0.003766
878.0      0.003555
916.0      0.003406
321.0      0.003315
157.0      0.003303
681.0      0.003266
223.0      0.003150
384.0      0.003042
478.0      0.003001
267.0      0.003001
759.0      0.002968
106.0      0.002922
404.0      0.002836
389.0      0.002728
750.0      0.002550
117.0      0.002513
258.0      0.002484


In [254]:
nyc_crime_race_reported.LAW_CAT_CD.value_counts(normalize=True)

MISDEMEANOR    0.486125
VIOLATION      0.262454
FELONY         0.251421
Name: LAW_CAT_CD, dtype: float64

In [255]:
nyc_crime_race_reported_sample.LAW_CAT_CD.value_counts(normalize=True)

MISDEMEANOR    0.487143
VIOLATION      0.261071
FELONY         0.251787
Name: LAW_CAT_CD, dtype: float64

The next couple cells of code csv export one DataFrame of the sample of all crimes, and then another DataFrame for only the sample of cases where the suspect's race was reported.

In [256]:
nyc_crime_sample.to_csv('nyc_crime_sample_HT.csv')

In [257]:
nyc_crime_race_reported_sample.to_csv('nyc_crime_race_reported_sample_HT.csv')